### ISSUE TITLE
zenodo failed

### ISSUE THREAD

**Issue by bjarthur** [dcjones/Gadfly.jl#1147]
perhaps because i, and not @tlnagy made the release.  would be nice to update the citation.

https://zenodo.org/account/settings/github/repository/GiovineItalia/Gadfly.jl#

also...  i uninstalled attobot because gadfly must be tagged at the same time as compose, ideally in the same PR to metadata.

**Comment by tlnagy** [comment]
AFAIK, it should update whenever any of us makes an official release (which you've already done). Not sure what else needs to happen to trigger it.

**Comment by bjarthur** [comment]
could you try clicking the manual sync button and toggling the repo on and off as described [here](https://github.com/zenodo/zenodo/issues/1181#issuecomment-347268243)?  not an option for us to remove the 'v' from the version title as that would be inconsistent with the rest of julia.  if that doesn't work then we can just hope for the best the next time we tag.

**Comment by tlnagy** [comment]
Unfortunately it looks like I don't have access to turn it off and on again.

![image](https://user-images.githubusercontent.com/1661487/40444358-0cdf89aa-5e7e-11e8-8219-ae98d058e9c3.png)

The error message is quite unhelpful: "an unknown error occurred"

**Comment by bjarthur** [comment]
strange, because is says your request was approved:

<img width="1117" alt="screen shot 2018-05-23 at 3 11 32 pm" src="https://user-images.githubusercontent.com/1538268/40446290-bd278e84-5e9c-11e8-8dd7-38e08ce862f0.png">

i've filled out the "contact us" form at zenodo and asked why it failed.

**Comment by bjarthur** [comment]
@dcjones zenodo customer support says you need to transfer Gadfly on their site from dcjones to GiovaneItalia:

> Dear Ben,
> It appears that the repository was previously named
> "dcjones/Gadfly.jl" and was later on transferred to "Giovane
> Italia/Gadfly.jl". The old owner of the repository (I guess the
> GitHub user "dcjones") has activated the repository on his own
> Zenodo GitHub account. If you can contact him and tell him to
> disable the repository so that you (or the GitHub's
> "GiovineItalia" organization owner) can enable it on Zenodo, we
> can retry the release for "v0.7.0".
> 
> Let me know when you are ready, or if you have any questions.
> 
> Best regards,Alex Ioannidis
> 
> Zenodo Support
> https://zenodo.org ( https://zenodo.org )
>

**Comment by tlnagy** [comment]
Thanks for looking into that. I sent Daniel an email with that information and I update here once I hear back from him.

**Comment by dcjones** [comment]
I've disabled the repo on my zenodo account now. Let me know if I need to do anything else.

**Comment by bjarthur** [comment]
@tlnagy zenodo's website still says "this repo is managed by another user..." for me.  can you check to see if you can enable it?

**Comment by tlnagy** [comment]
I toggled it yesterday after Daniel switched it over and couldn't see any changes. I disabled it again so you should be able to take control.
