### ISSUE TITLE
Better label placement in bar charts

### ISSUE THREAD

**Issue by jiahao** [dcjones/Gadfly.jl#116]
```julia
using DataFrames
using Gadfly
plot(DataFrame(Name=["a", "b", "c", "d", "e", ], Points=[14, 11, 8, 7, 6]),
     y=:Points, x=1:6, label=:Name, Geom.label, Geom.bar)
```
![untitled](https://f.cloud.github.com/assets/1732/1529010/ce9cde44-4c22-11e3-9620-3bd685b82a55.png)

The label of the tallest bar is consistently not drawn (presumably because it is off the scale). It would also be nice if the labels were aligned consistently to the top of the bar.

```julia
plot(DataFrame(Name=["AAA", "BB", "CCCC", "DDD", "EEEEEE", "F", "GG", "HHH", "II", "J"], Points=[14,11,8,7,6,4,3,2,1,0]),
     y=:Points, x=1:10, label=:Name, Geom.label, Geom.bar)
```
![untitled](https://f.cloud.github.com/assets/1732/1529022/c8d880c0-4c23-11e3-8579-1baaa9735d5c.png)

**Comment by dcjones** [comment]
I think this fixed, since you can manually align labels these days.

<img width="531" alt="screen shot 2015-09-16 at 11 57 36 pm" src="https://cloud.githubusercontent.com/assets/210361/9926937/d93b3e36-5cce-11e5-8caa-80fc512ba521.png">
