### ISSUE TITLE
Datetime support

### ISSUE THREAD

**Issue by bp2012** [dcjones/Gadfly.jl#138]
Issue 78 was a great step forward in supporting the Date type. Would it be possible to add support for Datetime types? I have some 5 minute interval data that I would love to be able to plot.

Thanks!

**Comment by dcjones** [comment]
I think this works adequately now. Feel free to open a specific issue if that's not the case.
<img width="714" alt="screen shot 2015-09-17 at 12 28 33 am" src="https://cloud.githubusercontent.com/assets/210361/9927388/180f4ee6-5cd3-11e5-9690-8afe04ec3c02.png">
