### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by devmotion** [dcjones/Gadfly.jl#1551]
I noticed Distributions 0.25 is supported on the master branch but there's no official release that supports it yet. Would it be possible to make a new release? The missing compatibility with Distributions 0.25 causes e.g. errors when building the documentation of MCMCChains in https://github.com/TuringLang/MCMCChains.jl/pull/310.

**Comment by mschauer** [comment]
Ping, we would need that if we want to use Gadfly in the Docs

**Comment by bjarthur** [comment]
i've been hoping to resolve https://github.com/GiovineItalia/Gadfly.jl/pull/1553 before tagging a new release

**Comment by bjarthur** [comment]
will release a new version once https://github.com/GiovineItalia/Gadfly.jl/pull/1554 passes CI.  thanks for your patience.

**Comment by bjarthur** [comment]
https://github.com/JuliaRegistries/General/pull/46448

**Comment by devmotion** [comment]
Thank you for the new release! This will help us in MCMCChains a lot 🙂
