### ISSUE TITLE
"Bring your own shape" geometry

### ISSUE THREAD

**Issue by Keno** [dcjones/Gadfly.jl#168]
I have a set of data that I'm plotting on top of a map of the united states. I'm generating compose canvases for all the individual counties and it works very well, but I've been thinking about how to integrate this into Gadfly. What I came up with is basically a geometry that lets you specify your own Compose shape to be drawn (think of it like Geom.rectbin, but instead of rectangles you specify your own function to draw a compose object). With that something like this would be possible:

```
plot(data, shape="FIPS", shapefunc=draw_county, color="population", Geom.whatever)
```

which would draw a population heatmap. In this particular example `draw_county(FIPS)` would return a compose canvas for the county with the given FIPS code. Of course the interface can be debated about, but that's the basic idea. The geometry would possibly need to take some arguments such as the UnitBox for the shapes, but that's a detail.

**Comment by dcjones** [comment]
There's now a `Geom.polygon` to draw polygons from coordinates, and `Guide.annotation` which can draw them directly with compose, so I'm calling this one done.
