### ISSUE TITLE
Various features (some simple, some more challenging)

### ISSUE THREAD

**Issue by papamarkou** [dcjones/Gadfly.jl#201]
I like Gadfly a lot, only started using it yesterday. Being not so familiar with it, there were several features I wondered if they are available, so please excuse my lack of knowledge if some of the features I mention below are present in the package. As a user, I identified some functionality that may be useful to (me and) other users too. Rather than opening several separate tickets, I thought I may provide a list below with the desired features to find out which ones may be available, which ones are easy to code and which ones would need a lot of work. So here is the list:
1. Transparent background; is it easy to set `panel_fill` to transparent (rather than white)?
2. Specify style (symbol) for plotting points (similear to R's `pch` option).
3. Specify style of black-coloured lines (dotted, dashed, dotted-dashed, apart from solid).
4. Use of basic LaTeX (subscripts, superscripts etc) for annotation in labels and legends (this may already be available).
5. Saving in JPG format.
6. 3D plots (I guess the last two are somewhat more challenging).

This is a very broad issue, mostly asking which of these are easier to add.

**Comment by scidom** [comment]
Hi @dcjones, I just noticed by accident your latest reply and that you have followed up with this. Thank you very much :)

**Comment by scidom** [comment]
Sure, feel free to close this one, I agree with you that it is better to break it down to sub-issues, which you have done already.
