### ISSUE TITLE
Feature Request: Candlestick Chart

### ISSUE THREAD

**Issue by aviks** [dcjones/Gadfly.jl#229]
So I wanted to be able to plot [candlestick charts](http://en.wikipedia.org/wiki/Candlestick_chart)

A boxplot get me part of the way there, with the following major caveats
1. Manually specify the `lower_hinge` and `upper_hinge`, rather than calculate the statistic (as the open and close prices). `upper_fence` and `lower_fence` are can be correcly calculated as the high and low, but if we're specifying the former, we might as well specify these. 
2. Invert the color if `lower_hinge > upper_hinge`
3. do not plot outlier.

**Comment by xgdgsc** [comment]
Is 2 possible?
