### ISSUE TITLE
loading Gadfly takes a long time

### ISSUE THREAD

**Issue by vks** [dcjones/Gadfly.jl#251]
Just loading it takes about 30 s on my machine. Is this normal? Why does it take so much time?

```
> time julia -e 'using Gadfly'
Warning: Possible conflict in library symbol dtrtri_
Warning: Possible conflict in library symbol dgetri_
Warning: Possible conflict in library symbol dgetrf_
Warning: could not import Base.foldl into NumericExtensions
Warning: could not import Base.foldr into NumericExtensions
Warning: could not import Base.sum! into NumericExtensions
Warning: could not import Base.maximum! into NumericExtensions
Warning: could not import Base.minimum! into NumericExtensions
Warning: could not import StatsBase.bandwidth into Stat
Warning: could not import StatsBase.kde into Stat
       29.34 real        29.03 user         0.27 sys
```

**Comment by ViralBShah** [comment]
FWIW, @tanmaykm does include Gadfly in the sys.ji on JuliaBox.

**Comment by tanmaykm** [comment]
Yes, Gadfly and its related packages are precompiled on JuliaBox and that makes it load almost instantaneously. Also, `reload` of the package works as @timholy mentioned.

**Comment by stevengj** [comment]
If you add `VERSION >= v"0.4.0-dev+6521" && __precompile__()` to the top of `Gadfly.jl` it will now (in the latest Julia 0.4-dev) precompile automatically the first time it is imported, and recompile automatically thereafter when any of the dependencies are updated.
