### ISSUE TITLE
Plots messed up with large numbers:

### ISSUE THREAD

**Issue by Keno** [dcjones/Gadfly.jl#266]
It seems like somewhere around 10^21, Gadfly gets confused about how much space the formatted numbers will take up: 
![screen shot 2014-04-07 at 1 31 55 pm](https://cloud.githubusercontent.com/assets/1291671/2634824/3354ec64-be7e-11e3-8b7c-c01f815d4821.png)

I think this is because for even high numbers we print way to many significant digits (Is that because 10^n isn't precisely representable anymore):
![screen shot 2014-04-07 at 1 59 23 pm](https://cloud.githubusercontent.com/assets/1291671/2634837/60083f54-be7e-11e3-8a5e-f09e71fa2f75.png)

**Comment by dcjones** [comment]
I think this works ok now.

<img width="512" alt="screen shot 2015-09-17 at 12 06 17 am" src="https://cloud.githubusercontent.com/assets/210361/9927070/fa4e9d6a-5ccf-11e5-9f9d-38c4a09160e6.png">
