### ISSUE TITLE
Heretical method only accepting y

### ISSUE THREAD

**Issue by tomaskrehlik** [dcjones/Gadfly.jl#309]
Hey there,

I often find myself doing exploratory analysis of some generated data and want to plot either one or several simulated time series in one plot. It would be great to have a heretical method that would simplify that by not requiring to specify x and potentially, if you would supply a matrix to y, it would output the series in various colors. Something in the spirit of this, if I would call plot(y=data, Geom.line):

````
C = [1 0.8; 0.8 1]
data=rand(MvNormal(C), 1001)
plot(layer(x=[1:1001], y=data[1,:]+4, Geom.line, Theme(default_color=color("orange"))), layer(x=[1:1001], y=data[2,:], Geom.line))
````

I think it would simplify life of many people doing the same thing and would make Gadfly more suited for the exploratory analysis.

**Comment by dcjones** [comment]
This works now:
<img width="612" alt="screen shot 2015-09-17 at 3 53 51 pm" src="https://cloud.githubusercontent.com/assets/210361/9948044/63054af0-5d54-11e5-84eb-f21a71415f44.png">

**Comment by timholy** [comment]
Nice, @dcjones. I'm sure I will enjoy this.
