### ISSUE TITLE
Ability to specify manual color keys

### ISSUE THREAD

**Issue by dcjones** [dcjones/Gadfly.jl#344]
Complex plots sometimes need complete control of the color key. Cc: @aviks

**Comment by marcjwilliams1** [comment]
Hi, I'm still getting this error. I'm using julia v0.3.1 and the latest gadfly on ijulia. Do I need a newer version of julia for this fix to work? Thanks Marc

**Comment by dcjones** [comment]
I just tagged a new version that includes Avik's fix, so it should work after updating.

**Comment by marcjwilliams1** [comment]
All working now. Thanks!
