### ISSUE TITLE
Date values not working with Geom.bar

### ISSUE THREAD

**Issue by jaydsolanki** [dcjones/Gadfly.jl#355]
I tried plotting date values with Geom.bar but it gives an error

Code-

``` julia
dates = Array(Date{ISOCalendar},40)
dates[1] = today()
for i=2:length(dates)
    dates[i] = today()+days(i)
end
draw(PNG("DatePlotBar.png",6inch,4inch),plot(x=dates,y=sort(rand(40)*40),Geom.bar))

ERROR: no method zero(Type{Date{ISOCalendar}})
 in render at /home/jaysolanki/.julia/v0.3/Gadfly/src/geom/bar.jl:244
 in render_prepared at /home/jaysolanki/.julia/v0.3/Gadfly/src/Gadfly.jl:718
 in render at /home/jaysolanki/.julia/v0.3/Gadfly/src/Gadfly.jl:673
 in draw at /home/jaysolanki/.julia/v0.3/Gadfly/src/Gadfly.jl:751
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
while loading /home/jaysolanki/SD/CurrencyReport/src/UnitTest/chart/datechart.jl, in expression starting on line 17
```

However it works without dates
`draw(PNG("DatePlotBarNoDate.png",6inch,4inch),plot(x[1:40],y=sort(rand(40)*40),Geom.bar,Theme(bar_spacing=0.75mm)))`

![dateplotbarnodate](https://cloud.githubusercontent.com/assets/6593003/3507945/1bf56776-0684-11e4-9b39-caa49a55d63b.png)

Please can you look into it?

**Comment by phil-pedruco** [comment]
Similar to jaydsolanki I've tried plotting date values with `Geom.bar`, but with the [Dates package](https://github.com/quinnj/Dates.jl).  Using the code:

    dates = [Date(2000,1,1):Day(1):Date(2000,12,1)]
    df = DataFrame(Dates = dt, Data = randn(length(dates)))

    plot(df, x="Dates", y="Data", Geom.bar)

This results the following error:

	ERROR: `/` has no method matching /(::Day, ::Millisecond)
	 in absolute_units at C:\Users\philipp\.julia\v0.3\Compose\src\form.jl:118
	 in draw at C:\Users\philipp\.julia\v0.3\Compose\src\form.jl:23
	 in drawpart at C:\Users\philipp\.julia\v0.3\Compose\src\container.jl:510
	 in draw at C:\Users\philipp\.julia\v0.3\Compose\src\container.jl:400
	 in display at C:\Users\philipp\.julia\v0.3\Gadfly\src\Gadfly.jl:1003
	 in display at C:\Users\philipp\.julia\v0.3\Gadfly\src\Gadfly.jl:149
	 in print_response at REPL.jl:139
	 in print_response at REPL.jl:124
	 in anonymous at REPL.jl:586
	 in run_interface at LineEdit.jl:1379
	 in run_frontend at REPL.jl:817
	 in run_repl at REPL.jl:169
	 in _start at client.jl:400

However, using `Geom.line` or `Geom.point` works as expected, also changing the x in `Geom.bar` to a range results in a chart as expected.

This was done using Julia  

    Version 0.3.4 (2014-12-26 10:42 UTC)
    Official http://julialang.org/ release
    x86_64-w64-mingw32

and `Gadfly 0.3.11` and `Dates 0.3.2`
