### ISSUE TITLE
Backend Selection for IJulia Notebooks

### ISSUE THREAD

**Issue by timothyrenner** [dcjones/Gadfly.jl#490]
For plots with a large number of elements (e.g. scatterplots with a bunch of points) the resulting SVG can gum up the browser, which isn't unexpected.

It would be nice to be able to select a backend or something (i.e. render the image as a PNG and show it) that wouldn't have the browser doing so much work for those types of plots.

At the moment, my workaround for plots like this is to use [Winston](https://github.com/nolta/Winston.jl), but it would be nice to be able to use Gadfly all the way through an analysis, even when the dataset has a lot of points.

**Comment by tonyduan** [comment]
@timothyrenner Did you end up finding a way to set PNG as the default for all plots in IJulia?

**Comment by timothyrenner** [comment]
I didn't, I just use the `draw(PNG(...), p)` trick.
