### ISSUE TITLE
Performance: 30 mins for plotting 10086 rows of record

### ISSUE THREAD

**Issue by nghenglim** [dcjones/Gadfly.jl#499]
train.csv: https://www.kaggle.com/c/bike-sharing-demand
Using laptop Asus F81s, window 7, 32 bit, with IJulia:

    using DataFrames #40sec
    df = readtable("train.csv") #7-8 sec - acceptable
    using Gadfly #about 50 sec
    plot(df, x="datetime", y="count", Geom.line) #30 mins

If I use excel, plot graph = 5 - 15 sec.

Some observation:
1. The x axis of the datetime, is too cramp after plotted the graph. It is unnecessary given that window size information can be obtained.
2. After the graph is plotted, the page is super slow and very likely to hang.
3. Performance...performance... plotting a graph which take 120 times longer than excel...

**Comment by dcjones** [comment]
The reason this is slow is because the dates in this data are treated as categories, and not dates. If you convert the data to the `DateTime` type like so, it takes 13 seconds to draw the plot the first time, and 0.2 seconds to draw it on subsequent calls.

```julia
df[:datetime] = [DateTime(t, "yyyy-mm-dd HH:MM:SS") for t in df[:datetime]]
```
