### ISSUE TITLE
Gallery section on Gadfly website

### ISSUE THREAD

**Issue by juliohm** [dcjones/Gadfly.jl#531]
One of the most helpful resources for learning the features of a plotting library is a collection of examples. I learned Matplotlib very easily by copying/pasting snippets of code that I found in their gallery: http://matplotlib.org/gallery.html

It would be nice to have the same documentation on the Gadfly website.

**Comment by aviks** [comment]
This would be good. Examples and/or a PR most welcome.

**Comment by juliohm** [comment]
@aviks, how to contribute examples to the website?

**Comment by vchuravy** [comment]
@juliohm as far as I know the gh-pages branch off Gadfly.jl contains the homepage 
https://github.com/dcjones/Gadfly.jl/tree/gh-pages

**Comment by juliohm** [comment]
@dcjones, so what is the desired approach? Suppose I have a snippet of code that does the plot, what do you want me to do?
