### ISSUE TITLE
Transparent background in PNG's

### ISSUE THREAD

**Issue by benhamner** [dcjones/Gadfly.jl#534]
All the plots produced using the PNG backend (at least on OS X) have a transparent background (panel_fill only affects the plot grid, not the entire plot).

Is there a way to set the entire plot background to opaque & white vs transparent by default, within the current API? This would make a better default.

**Comment by vchuravy** [comment]
You can currently do it by using `Compose.jl`

````julia
using Compose
using Gadfly

p = plot(x->x, 0,10)
compose(render(p), compose(context(), rectangle(), fill("white")))
````

I would debate that this would be a more useful default, since if you print out a figure for publication you don't want to have a different shade of white than the background of the paper. I agree that it is a bit annoying if you are using non white backgrounds, but that can be more easily solved.

**Comment by aviks** [comment]
I would also argue that transparent is a more useful default, since its easy to layer that with a white background, but certainly not easy to go the other way.

**Comment by benhamner** [comment]
Valentin - thanks, that's helpful. I'm adding that line wherever I'm generating plots that are saved to disk.

The challenge with the default is that it looks terrible when saved on OS X with a transparent background & then viewed using the default image viewer (Preview), plus that there isn't a clear and intuitive way to change this:

![image](https://cloud.githubusercontent.com/assets/582878/5893386/715d9f02-a496-11e4-91de-a571462d0083.png)

I'm not close enough to the design of Gadfly to know, but is there a reason why the plot API can't expose a background_color (or similarly named) theme option, so that changing it is a 10-character operation vs explicitly using another library + needing a much longer nonintuitive line?

For the ways I've used Gadfly so far, white would have been a better & simpler default. Regardless of the default, changing it to something else should be as simple as possible.

**Comment by dcjones** [comment]
I also prefer transparent as the default background. I guess I make a lot of off-white slides.

There's now a `background_color` parameter in Theme, so you can change it like:
```julia
plot(x=[1,2,3], y=[1,2,3], Geom.point, Theme(background_color=color("white")))
```
