### ISSUE TITLE
Output SVG to String

### ISSUE THREAD

**Issue by JonathanKnight** [dcjones/Gadfly.jl#535]
Is it possible to output a plot to an svg string rather than render to a file ? I would like to be able to store my plots as svg data rather than as files.

**Comment by darwindarak** [comment]
You can draw the plot to an in-memory buffer, then convert it into a string.  Something like

```julia
p = plot(x= rand(10), y = rand(10));

width = Compose.default_graphic_width
height = Compose.default_graphic_height

buf = IOBuffer()
draw(SVG(buf, width, height), p)

svg_string = takebuf_string(buf)
```

**Comment by aviks** [comment]
Closing, since this invocation by @darwindarak  is the canonical way to write this. Please comment or reopen if this does not solve your issue.
