### ISSUE TITLE
Feature request: disable label layout magics

### ISSUE THREAD

**Issue by IainNZ** [dcjones/Gadfly.jl#542]
My labels are being laid out "smartly" but not to my liking - I'd rather take some minor overlapping. It'd be neat to have an override.

**Comment by IainNZ** [comment]
Ah: `Theme(label_placement_iterations=0)` does this... maybe I could do a PR to advertise this in the `geom_label` manual page?

**Comment by dcjones** [comment]
Even better, now you can get static label layouts like `Geom.label(position=p)`, where `p` is one of `:left, :right, :above, :below, :centered`.

**Comment by IainNZ** [comment]
Neat :+1: !
