### ISSUE TITLE
Subplot Grid problems in v0.3.11

### ISSUE THREAD

**Issue by durcan** [dcjones/Gadfly.jl#547]
The upgrade from v0.3.10 to .0.3.11 has caused some problems with how various subplot grid items are plotted. The examples I have run into so far are Geom.histogram failing to have proper y scaling and Geom.point failing to pickup xgroup and instead repeatedly plotting the same plots again and again. (sorry about the horrible plots, I was just trying to quickly illustrate the point). All plots are on Julia 0.3.6-pre+53.

Examples:
with the same data, the following code

```julia
using RDatasets
using Lazy
using Gadfly
c = dataset("mlmRev", "Chem97")

@>> begin 
    plot(c,
    x=:GCSEScore,
    ygroup=:Age,
    color=:Gender,
    Geom.subplot_grid(Geom.histogram, free_y_axis=true))
    draw(PNG(10cm, 30cm))
end

```
Gadfly pined at v0.3.10 produces:
![plot 1]
(http://www.astro.caltech.edu/~bdc/hist_310.png)

Gadfly pined at v0.3.11 produces (note the top of some plots is cut off):
![plot 2]
(http://www.astro.caltech.edu/~bdc/hist_311.png)

For Geom.point the following code:
```julia
@>> begin
    plot(c,
    x=:GCSEScore,
    ygroup=:Gender,
    xgroup=:Score,
    y=:Age,
    Geom.subplot_grid(Geom.point, free_y_axis=true),
    Theme(default_point_size=0.1mm, highlight_width=0.0mm))
    draw(PNG(30cm, 10cm)) 
end
```

In 0.3.10 produces (note the differences between horizontal plots):
![plot 3]
(http://www.astro.caltech.edu/~bdc/point_310.png)

In 0.3.11 produces (note the different horizontal plots are all the same...this is wrong):
![plot 4]
(http://www.astro.caltech.edu/~bdc/point_311.png)

I have had a brief look at the changes between the two releases but I have not seemed to track the problem down.

**Comment by dcjones** [comment]
Thanks for the test cases!

**Comment by durcan** [comment]
Holy cow. Closed overnight. I am impressed.
