### ISSUE TITLE
Geom.histogram should use y minvalue = 0

### ISSUE THREAD

**Issue by julian-gehring** [dcjones/Gadfly.jl#552]
Plotting a histogram like

```julia
x = randn(1000);
plot(x = x, Geom.histogram(bincount = 10))
```

by default limits the y-axis to the range used by the bin counts (in the example, to [80,120]):

![test](https://cloud.githubusercontent.com/assets/302566/6328746/c66800ce-bb6a-11e4-94c1-fbf1cec1c5d3.png)

Since the absolute number of counts in each bin is of relevance here, it should extend the y-axis to include 0 as a lower limit:

```julia
plot(x = x, Geom.histogram(bincount = 10), Scale.y_continuous(minvalue = 0))
```

![test2](https://cloud.githubusercontent.com/assets/302566/6328784/345678a4-bb6b-11e4-849b-4ef1064aa07b.png)

See also the `hist` function in base R and `geom_hist` in `ggplot2`.

**Comment by dcjones** [comment]
Yeah, that's definitely not a good default.
