### ISSUE TITLE
Should plotting range always contain hlines?

### ISSUE THREAD

**Issue by jiahao** [dcjones/Gadfly.jl#557]
Consider this code and the resulting plot:

```jl
plot(
    x=1:5, y=11:15, Geom.line, Geom.point,
    yintercept=[1.], Geom.hline,
)
```

![screen shot 2015-03-06 at 11 55 38 am](https://cloud.githubusercontent.com/assets/1732/6529602/eb05bc2e-c3f7-11e4-91d0-c7c14acc2804.png)

Would it be reasonable to assume that if one bothers to specify `yintercept`s that one cares about, that the plotting range should be adjusted so that the corresponding `hline`s are always visible on the plot? Currently the plotting range has to be adjusted explicitly by specifying something like `Coord.Cartesian(ymin=1.0)`.

![screen shot 2015-03-06 at 11 56 29 am](https://cloud.githubusercontent.com/assets/1732/6529604/ef5e5074-c3f7-11e4-81cf-acbfd4c7e039.png)

Similar considerations apply for `xintercept`s and `vline`s, of course.

**Comment by dcjones** [comment]
Yep, I think it should, I just overlooked it.
