### ISSUE TITLE
Plot Polygon

### ISSUE THREAD

**Issue by gestay** [dcjones/Gadfly.jl#561]
Is it possible to plot a (non-self-intersecting) polygon from its vertex coordinates? I mean something like this:

```julia
#Unsorted coorditates:
x = [0, -4, 0, 4, -1, -1, 1, 1] + 3
y = [4, 0, -4, 0, 1, -1, -1, 1] - 1

#Centroid coordinates
Cx = sum(x) / length(x)
Cy = sum(y) / length(y)

theta = atan2(y - Cy,x - Cx)
p = sortperm(theta)

x = x[p]
y = y[p]

x = [x; x[1]]
y = [y; y[1]]

plot(x = x, y = y, Geom.point, Geom.path)
```

I think the above works, but It would be nice to have to have something like:

```julia
plot(x=x, y=y, Geom.polygon)
```

Thanks.

**Comment by binarybana** [comment]
For reference, this is discussed in #168.

**Comment by binarybana** [comment]
Oh, and it looks like this should be fairly straightforward (although I still like @gestay 's API better) using [Guide.annotation](http://gadflyjl.org/guide_annotation.html) assuming your plotting your polygon on top of something.

**Comment by dcjones** [comment]
```julia
plot(x=[0, 1, 1, 2, 2, 3, 3, 2, 2, 1, 1, 0, 4, 5, 5, 4],
     y=[0, 0, 1, 1, 0, 0, 3, 3, 2, 2, 3, 3, 0, 0, 3, 3],
     group=["H", "H", "H", "H", "H", "H", "H", "H",
            "H", "H", "H", "H", "I", "I", "I", "I"],
     Geom.polygon(preserve_order=true, fill=true))
```
![try](https://cloud.githubusercontent.com/assets/210361/6889933/ba4b6cda-d655-11e4-8d4c-95bdd1605876.png)
