### ISSUE TITLE
Line plotting breaks when encountering a datapoint surrounded by NaN

### ISSUE THREAD

**Issue by vchuravy** [dcjones/Gadfly.jl#566]
So when plotting data with `NaN` to signal discontinuities `Geom.line` and `Geom.path` break when encountering a datapoint surrounded by `NaN` 

The code below works as expected
````julia
data = Float64[1.0, 2.0, NaN, 4.0, 5.0]
plot(x = 1:length(data), y = data, Geom.line)
````
also this works
````julia
data = Float64[1.0, 2.0, NaN, 4.0, 5.0, NaN, 7.0, 8.0]
plot(x = 1:length(data), y = data, Geom.line)
````

But when having `NaN, 4.0, NaN`
````julia
data = Float64[1.0, 2.0, NaN, 4.0, NaN, 6.0, 7.0]
plot(x = 1:length(data), y = data, Geom.line)
````

the data beyond the anomaly is not plotted any more. I think it would fine to either drop the point or add a mode to `Geom.line` where all discontinuities are surrounded by `Geom.point`.

**Comment by dcjones** [comment]
Funnily enough, this worked as expected on the cairo (PNG, PDF, PS) backends, but not on the others. That's fixed on Compose master now.

**Comment by vchuravy** [comment]
Thanks :+1: No longer plots that mysteriously disappear.
