### ISSUE TITLE
Scale.x_sqrt shows incorrect labels

### ISSUE THREAD

**Issue by JonathanKnight** [dcjones/Gadfly.jl#568]
When setting a scale to x_sqrt the labels are shown as the sqrt of the actual values. It looks like the labels are transformed as well as the scale.

**Comment by dcjones** [comment]
I'm not sure I follow. This is what I see:
```julia
plot(x=100.0 * rand(100), y=100.0 * rand(100), Geom.point, Scale.x_sqrt)
```
![try](https://cloud.githubusercontent.com/assets/210361/6861754/c27db714-d3f8-11e4-9a14-83e5f173bfce.png)

It shows e.g. 10², not 10. Do you get something else?

**Comment by JonathanKnight** [comment]
Aha - that is making sense becuase I am using a label formatter so this

plot(x=100*rand(100), y=100*rand(100), Geom.point, Scale.x_sqrt(labels = x -> format(x,precision=2))) gives this

![screenshot from 2015-03-27 14 10 46](https://cloud.githubusercontent.com/assets/590202/6869326/2476629e-d48b-11e4-8ca2-5f876ad5b93f.png)

So if I want the axis labels to be correct I have to use this 

plot(x=100*rand(100), y=100*rand(100), Geom.point, Scale.x_sqrt(labels = x -> format(x*x,precision=2))) to give this

![screenshot from 2015-03-27 14 12 23](https://cloud.githubusercontent.com/assets/590202/6869351/584c52b8-d48b-11e4-8318-eb495f785108.png)

**Comment by dcjones** [comment]
Oh that's right, label values are passed to formatting functions transformed. I've tried to clarify that in the manual now.
