### ISSUE TITLE
Can't open eps files generated by draw

### ISSUE THREAD

**Issue by Balinus** [dcjones/Gadfly.jl#576]
Here's the code I use to generate the eps file : 

fgPlot=plot(x=collect(1:100), y=sort(rand(100)))
draw(SVG("myplot.png", 6inch, 3inch),fgPlot)

Then, I get the following error when i try to open the file with Inkscape :
ps2pdf failed:

Error: /syntaxerror in -file-
Operand stack:

Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   1916   1   3   %oparray_pop   1915   1   3   %oparray_pop   1899   1   3   %oparray_pop   1787   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push
Dictionary stack:
   --dict:1176/1684(ro)(G)--   --dict:0/20(G)--   --dict:77/200(L)--
Current allocation mode is local
Current file position is 1
GPL Ghostscript 9.10: Unrecoverable error, exit code 1

Tried multiple software and still can't open the eps files. Though, I can open the file with Gimp, but I get a transparent background instead of a white background.

My system:
Ubuntu 14.04 (64 bits)
Juno IDE
Julia 0.3.7

**Comment by darwindarak** [comment]
You are using the SVG backend and saving to a file with *.png extension. Did you mean
```julia
draw(PS("myplot.ps", 6inch, 3inch),fgPlot)
```
instead?

**Comment by Balinus** [comment]
ah, bingo! Sorry for that, I'm still quite new to Julia. I didn't noticed the choice of backend inside the draw function.

Thanks!
