### ISSUE TITLE
Broken mouseover with Geom.bar on js.svg backend?

### ISSUE THREAD

**Issue by amellnik** [dcjones/Gadfly.jl#579]
Any chart I generate with Geom.bar and the default backend has an issue where when I mouseover the plot, the grid lines get thicker as intended, but when I un-mouseover they don't shrink back to normal size.  Every time I do this they get thicker and eventually they just become a solid grey background.  Verified in both IE and Chrome, but I noticed that this doesn't happen in the bar plot shown on the manual page -- maybe it's already been fixed and I wasn't able to find the commit, or maybe these were generated with a previous version of Gadfly?  I've only seen it in bar, but i haven't exhaustively checked other geometries.

**Comment by dcjones** [comment]
I just checked in chrome, firefox, and safari on osx and it works. If convenient, could use master on Compose/Gadfly (`Pkg.checkout("Compose"); Pkg.checkout("Gadfly")`) to generate a plot and see if it still happens? I'll try it out on windows when I have a chance.

**Comment by amellnik** [comment]
I just made a clean install at home with the current release and it's working as intended.  I'll take another look at work on Monday, and report back if I see anything, but perhaps it was fixed very recently or maybe a windows 8 verses 7 issue.

**Comment by amellnik** [comment]
Ok, it turns out this appears to be an issue with Guide.xticks().  Here's a minimal example to reproduce:

    using DataFrames, Gadfly
    data = DataFrame()
    data[:turtle] = ["Suzy", "Suzy", "Bob", "Batman", "Batman", "Batman", "Bob"]
    data[:time] = [6.2 , 6.7 , 2.1, 3.2, 3.1, 0.9, 2.4]
    data[:photo] = ["111.jpg","123.jpg","145.jpg","167.jpg","189.jpg","190.jpg","195.jpg"]

    #Works
    nWafersPlot= plot(data, x="turtle", y="time", Geom.bar)

    #Does not work
    nWafersPlot= plot(data, x="turtle", y="time", Geom.bar, Guide.xticks(label=false) )

Something about hiding xticks is messing up the mouseover code.  It's also nothing specific to bar, it also happens on line for example (I had a bunch of plots and the only one I was hiding xticks on was the bar one).

**Comment by dcjones** [comment]
Should be fixed now. Thanks for the test case.

**Comment by amellnik** [comment]
Great, thanks!
