### ISSUE TITLE
Keep data ordered in histogram?

### ISSUE THREAD

**Issue by amellnik** [dcjones/Gadfly.jl#584]
Would it be possible to make categorical histograms keep their sorting order in the category?  I'm having a hard time following the code for histograms but perhaps it was already meant to do this?  Categorical boxplots, for example, keep this ordered.  Thanks -A

**Comment by amellnik** [comment]
And just to follow up, while categorical boxplots do maintain their sorting, if you then define a color for dodged or stacked bars the sorting is lost.

**Comment by dcjones** [comment]
Could you give me an example for what you mean. It seems to me that categorical histograms to keep the order of the data by default:

```julia
df = DataFrame(
    x=["A", "A", "B", "B", "C", "C"],
    y=[1, 1, 1, 1, 1, 1])

plot(df, x=:x, y=:y, Geom.histogram)
```
![try](https://cloud.githubusercontent.com/assets/210361/7205985/224508ba-e4e2-11e4-9040-b95dd5f88b74.png)

```julia
df = DataFrame(
    x=["C", "C", "B", "B", "A", "A"],
    y=[1, 1, 1, 1, 1, 1])

plot(df, x=:x, y=:y, Geom.histogram)
```
![try](https://cloud.githubusercontent.com/assets/210361/7206003/410d79b2-e4e2-11e4-8026-0bb201ba6803.png)

**Comment by amellnik** [comment]
I'm not able to reproduce now, it looks like I probably screwed up the sort key when I sorted.  Note to self: don't post an issue without demo code to reproduce...
