### ISSUE TITLE
v0.4 Tuple changes cause failure to load

### ISSUE THREAD

**Issue by sebastiang** [dcjones/Gadfly.jl#586]
First error is in `Compose`, but likely are in other places

    ERROR: LoadError: LoadError: LoadError: invalid union type
    while loading .julia/v0.4/Compose/src/property.jl, in expression starting on line 453
    while loading .julia/v0.4/Compose/src/Compose.jl, in expression starting on line 61
    while loading .julia/v0.4/Gadfly/src/Gadfly.jl, in expression starting on line 6

Which are areas where Type unions are declared such as `Union(Nothing, (String,String))` instead of the new syntax `Union(Nothing, Tuple{String,String})`.

**Comment by IainNZ** [comment]
Would be good to get a Compat.jl-based fix for any of them you can get to - theres probably quite a few

**Comment by sebastiang** [comment]
Was actually knocking them out for 20 minutes, but some of the tests failed and I felt a little lost on fixing them. I can take another run at it if you think the mechanical transformation is correct.

On April 21, 2015 at 8:22:34 PM, Iain Dunning (notifications@github.com) wrote:
Would be good to get a Compat.jl-based fix for any of them you can get to - theres probably quite a few

**Comment by dcjones** [comment]
There are also a bunch of dependencies that need to be updated before gadfly will work on 0.4. I did that for Hexagons and Contour today. It's currently failing on Grid by way of KernelDensity for me.

**Comment by sebastiang** [comment]
A true test of our commitment to an ever-changing open source product, then eh? Guess it’s time to step up. :-D

**Comment by sebastiang** [comment]
Requires fix to tlycken/Contour.jl#20

**Comment by sebastiang** [comment]
Pull request submitted for the failures in `Grid` (https://github.com/timholy/Grid.jl/pull/59) due to vararg tuples finally gets me to `KernelDensity`

**Comment by sebastiang** [comment]
And a pull request sent into `KernelDensity` as well (https://github.com/JuliaStats/KernelDensity.jl/pull/14) but it doesn't entirely solve the problem. Something funny is going on with dispatch that I don't understand.

**Comment by sebastiang** [comment]
OK, have it loading. Pull requests https://github.com/timholy/Grid.jl/pull/59 and https://github.com/JuliaStats/KernelDensity.jl/pull/14 and https://github.com/tlycken/Contour.jl/pull/20 have all been merged so if you're tracking `master` on those packages you're in good shape. I'll create a PR with this, but would love to improve it or hand it off to actually pass tests. At the moment I'm getting 

    ERROR: LoadError: SystemError: opening file output/points.tex: No such file or directory
     ...
     in call at .julia/v0.4/Compose/src/pgf_backend.jl:116
     in anonymous at .julia/v0.4/Gadfly/test/runtests.jl:105
    ...

And indeed no such file exists in the source repo. I'm guessing this is either because a test failed previously that was supposed to put a file there, or there's some additional data I need to run the tests?

**Comment by dcjones** [comment]
I pushed what I have, but not everything is working. Remaining problems that I know of:

  * Color keys are misdrawn due to a weird julia bug:

```julia
using Compose
@show 1*cy == cy # true
for i in 1:1
    @show i*cy == cy # false (wtf...)
end
```
  * I had a few random segfaults in cairo.
  * The raster test fails. I haven't investigated this yet.
  * It's now broken by https://github.com/JuliaLang/julia/pull/10951, since Base and Gadfly both have modules named Stat. I don't know how to address that.

Can we just stay with Julia 0.3 forever? I liked 0.3...

**Comment by ZacCranko** [comment]
You can do it @dcjones, I have faith! Everything other than Gadfly is just dreadful... I can't go back

**Comment by dcjones** [comment]
Ok, everything should work on 0.4 now. You'll need to be on master on a number of packages, though I'm not sure exactly which at this point.

**Comment by bfredl** [comment]
It [pre]compiles and works fine for me after checking out Countour, Grid, KernelDenstity and Optim to to master.
