### ISSUE TITLE
xticks example does not work

### ISSUE THREAD

**Issue by Keno** [dcjones/Gadfly.jl#593]
I was trying to figure out how to use `xticks`, but the example given in the documentation does not work:
```
julia> plot(x=rand(10), y=rand(10),
            Stat.xticks(ticks=[0.0, 0.1, 0.9, 1.0]), Geom.point)
ERROR: ArgumentError: function xticks does not accept keyword arguments
```
Was this changed? Does the documentation need to be updated?

**Comment by amellnik** [comment]
I'm not sure what the history is of this, but the following works (Guide.xticks rather than Stat.xticks)

    ticks = [0.1, 0.3, 0.5]
    plot(x=rand(10), y=rand(10), Geom.line, Guide.xticks(ticks=ticks))

**Comment by amellnik** [comment]
Edit: There's some sort of bug in the documentation web site, clicking on "xticks" in the Guide section takes you to the correct page but shows it highlighted in the Stats section, clicking on the "xticks" in the Stats section shows you the version with the code that doesn't work
