### ISSUE TITLE
BUG: Y-axis scale broken in subplot_grid

### ISSUE THREAD

**Issue by GravityAssisted** [dcjones/Gadfly.jl#594]
Hi,

I am trying to make a plot using `subplot_grid` as follows (`Results` is a DataFrame):
```julia
myplot =plot(Results,y="Escape_Vinf",x="TOF", xgroup="NumFlyby", ygroup="KBO",color="Perhellion_solar_radii", Geom.subplot_grid(Geom.point,free_y_axis=true),Theme(default_point_size=0.1mm,highlight_width=0.001mm))
```
but the resulting plot is wrong. All the plots on the `x-axis` are plotting the same data. If I remove `free_y_axis=true` and run this command:
```julia
myplot =plot(Results,y="Escape_Vinf",x="TOF", xgroup="NumFlyby", ygroup="KBO",color="Perhellion_solar_radii", Geom.subplot_grid(Geom.point),Theme(default_point_size=0.1mm,highlight_width=0.001mm))
```
Then it seems to plot just fine but of course the scales on the Y axis are not what I want. I also tried using custom ticks but they seem to get deactivated like mentioned in #221 

I read in one of the previous posts #547 that @dcjones corrected this `free_y_axis` issue, but it seems to still be broken. Maybe the changes didn't get merged ? 
I am using Gadfly ver 0.3.11. I even tried rolling back to version 0.3.10 by using the `Pkg.pin` function but it didn't help.

thanks

**Comment by dcjones** [comment]
It looks like I fixed #547 right after I tagged 0.3.11, and I haven't tagged a new version since. I'll do that tonight.

**Comment by GravityAssisted** [comment]
Wow... Sounds good ! I also found out that `Scale.color_continuous(minval=A,maxval=B)` seems to get ignored in `subplot_grid` . Maybe that was intentional but should be mentioned in the documentation, if that is the case.

**Comment by GravityAssisted** [comment]
Seems to be working now ! Thats a quick turnaround.. very awesome :+1:
