### ISSUE TITLE
Any way to adjust width of boxes in boxplot with Scale.x_continuous?

### ISSUE THREAD

**Issue by amellnik** [dcjones/Gadfly.jl#596]
I'm making a boxplot of some value broken up by weeks of the year.  A simple example is with the following:

    using DataFrames, Dates, Gadfly
    df = DataFrame()
    df[:Date] = [Date(2012),Date(2012),Date(2012,6),Date(2012,6),Date(2012,6),  Date(2014),Date(2014)]
    df[:Score] = [2,3,5,5,7,3,6]
    plot(df, x="Date", y="Score", Geom.boxplot(), Scale.x_continuous(labels=x -> string(Dates.year(x))))

![image](https://cloud.githubusercontent.com/assets/7132414/7618325/41040862-f966-11e4-9236-d21a1c852603.png)

First, I am impressed Gadfly plays so nicely with Dates.  DCJones might be a wizard.  

However, I'm now spoiled by the wizardry and want more.  Is there any way to adjust the width of the boxes in a boxplot?  I would like to be able to make sure that the boxes don't overlap each other while still using Scale.x_continuous.  I would use a discrete scale, except my real data set has missing data for many weeks and I would like to leave blanks in those weeks.  The bar geometry has xmin and xmax -- could this perhaps be extended here?

**Comment by amellnik** [comment]
I'll see if I can come up with a way to do this over the weekend.  As far as I can tell the general idea would be to add a "box_width" aesthetic for boxplots, and then check for its definition and fall back to 

    bw = 1w / n - theme.boxplot_spacing # boxplot width

if it's not defined.

**Comment by amellnik** [comment]
Well I got a little further.  I can add the argument (not aesthetic like I first thought) with something like

    immutable BoxplotGeometry <: Gadfly.GeometryElement
        box_width
	    #Don't have access to what we need to define the default box width here,
	    #so if it is undefined, set it to a placeholder value
	    function BoxplotGeometry(;box_width="default") 
		    new(box_width)
	    end
    end

but I can't figure out how to use the value passed with box_width to set bw, which has type
  
    Measure{MeasureNil,MeasureNil}

I also don't understand where w is being defined.  Any suggestions?

**Comment by dcjones** [comment]
Thanks for looking into this! Adding an option to control the boxplot width is a good idea, but in the example you gave, Gadfly should just be smart enough not to draw something so broken. I'll see if I can find a nicer solution.

> I also don't understand where w is being defined. Any suggestions?

`w` is a constant that's exported by Compose. It's represents the width of the context being drawn on. In this case, it's the width of the plot panel. So the logic there if there are `n` boxes, each should be `w / n` wide. But this obviously breaks when they are placed at different places on the x-axis like in your example.

**Comment by dcjones** [comment]
How's this?
![try](https://cloud.githubusercontent.com/assets/210361/7671872/907e29b4-fc94-11e4-8643-f04767855435.png)

**Comment by amellnik** [comment]
Looks good! 

Unrelated to Gadfly but mildly interesting: I did notice an issue with Dates while testing it.  If I use slightly more interesting dates

    df[:Date] = [Date(2012,1,1),Date(2012,1,1),Date(2012,1,8),Date(2012,1,8),Date(2012,1,22),  Date(2012,1,22),Date(2012,1,22)]
    df[:Score] = [2,3,5,5,7,3,6]

I get an error like 

   `/` has no method matching /(::Millisecond, ::Day)

     in absolute_x_position at C:\Users\Alex\.julia\v0.3\Compose\src\measure.jl:916
     in absolute_units at C:\Users\Alex\.julia\v0.3\Compose\src\form.jl:350
     in draw at C:\Users\Alex\.julia\v0.3\Compose\src\form.jl:23
     in drawpart at C:\Users\Alex\.julia\v0.3\Compose\src\container.jl:510
     in draw at C:\Users\Alex\.julia\v0.3\Compose\src\container.jl:400
     in writemime at C:\Users\Alex\.julia\v0.3\Gadfly\src\Gadfly.jl:884
     in sprint at iostream.jl:229
     in display_dict at C:\Users\Alex\.julia\v0.3\IJulia\src\execute_request.jl:28

In fact, you can't even do entirely sensible things like 

    (Date(2014,1,1) - Date(2012,5,4))/Dates.Week(1)

Luckily there's an easy work around, which is to use unix time:

    using DataFrames, Dates, Gadfly
    df = DataFrame()
    df[:Date] = [Date(2012,1,1),Date(2012,1,1),Date(2012,1,8),Date(2012,1,8),Date(2012,1,22),  Date(2012,1,22),Date(2012,1,22)]
    df[:Score] = [2,3,5,5,7,3,6]
    df[:unixTime]=0
    for i=1:nrow(df)
        df[i,:unixTime]=datetime2unix(DateTime(df[i,:Date]))
    end
    plot(df, x="unixTime", y="Score", Geom.boxplot(), 
    Scale.x_continuous(labels = x -> string(Dates.year(unix2datetime(x)),"-",Dates.week(unix2datetime(x)))))

![gadfly test plot](https://cloud.githubusercontent.com/assets/7132414/7672107/595c4c34-fc9b-11e4-9089-1bcbeaf7de84.PNG)

which works great, except for the fact that Dates thinks that January 1st and January 8th are in the same week.  Luckily that also has a work-around... -A
