### ISSUE TITLE
Wasted space when plotting large numbers

### ISSUE THREAD

**Issue by vchuravy** [dcjones/Gadfly.jl#597]
So when I plot a dataset containing fairly large numbers for the x-variable Gadfly tends to waste a bit of space. The space to the right of the plot below looks a bit weird when preparing a plot for a paper.

````
using Gadfly
plot(x = 1:1200, y = rand(1200), Geom.line, Scale.x_continuous(maxvalue=1200))
````

Also I would expect that if I set a maxvalue for the scale that it is taken as a hard requirement.

**Comment by dcjones** [comment]
The algorithm that choses grid lines has a number of knobs one can turn. So it's pretty easy to get a result like this by increasing one of the weights.
![try](https://cloud.githubusercontent.com/assets/210361/7695742/f5eaca0e-fda8-11e4-8b2b-a842809342d8.png)
Would exposing those parameters work for you?

> Also I would expect that if I set a maxvalue for the scale that it is taken as a hard requirement.

It choses ticks that encompass that value, with a penalty for going far beyond it. It might make sense have a separate parameter with which to contain the ticks.

**Comment by vchuravy** [comment]
Yes exposing knobs sounds like a good solution. The Heuristics is pretty good, but in cases like this it would be nice to be able to change them.

**Comment by dcjones** [comment]
Ok, this should get the desired result now.
```julia
pl = plot(x = 1:1200, y = rand(1200), Geom.line,
          Stat.xticks(coverage_weight=1.0),
          Scale.x_continuous(maxvalue=1200))
```
