### ISSUE TITLE
Circle Swatch in Legend - Final Circle Missing

### ISSUE THREAD

**Issue by Wedg** [dcjones/Gadfly.jl#605]
Hi there,

When changing the legend to "colorkey_swatch_shape=:circle" the final label color goes missing. E.g. see image below produced by the following:

df1 = DataFrame(x = rand(10), y = rand(10), label="A")
df2 = DataFrame(x = rand(10), y = rand(10), label="B")
df3 = DataFrame(x = rand(10), y = rand(10), label="C")
df = [df1; df2; df3]
plot(df, x="x", y="y", color="label", Theme(colorkey_swatch_shape=:circle), Geom.point)

![circle](https://cloud.githubusercontent.com/assets/8735697/8180443/12c73f82-141e-11e5-8b54-e5abde27e23f.png)

Am using Julia v0.3.8 and Gadfly v0.3.12

**Comment by dcjones** [comment]
This is fixed in master (by https://github.com/dcjones/Gadfly.jl/commit/f8d5d3ccd248445e604b807fa39ea75a2ae94449).
