### ISSUE TITLE
Geom.bar - negative bars

### ISSUE THREAD

**Issue by emilbayes** [dcjones/Gadfly.jl#628]
I'm having trouble drawing negative bars with `Geom.bar`. Here's a minimal example:

```julia
using Gadfly
plot(x=[1, 2, 3, 4], y=[-1, 2, -3, 1], Geom.bar)
```

Results in:
![Example](http://i.imgur.com/cDJeYRn.png)

I'm using Gadfly `0.3.13` and Julia `0.3.10`

**Comment by amellnik** [comment]
Interestingly (on live) having all negative values for y shows a blank plot with the intended range on the y axis, but having even a single positive value causes them to all show up as positive with the range as above.
