### ISSUE TITLE
deprecated syntax warning and not recognizing Cairo as installed

### ISSUE THREAD

**Issue by CNOT** [dcjones/Gadfly.jl#637]
Recently when I've tried to use Gadfly, I get a million warnings. For example this very simple code:

    using Gadfly
    p=plot(x=rand(10), y=rand(10), Geom.point, Geom.line)
    draw(PNG("test.png", 4inch, 3inch), p)

gives me warnings like(I can attach the whole list of warnings if someone is interested):

    WARNING: deprecated syntax "HashDict{K} (" at /home/sayed/.julia/v0.4/DataStructures/src/hashdict.jl:77. Use "HashDict{K}(" instead.
    WARNING: deprecated syntax "Base.sort (" at /home/sayed/.julia/v0.4/DataFrames/src/abstractdataframe/sort.jl:305. Use "Base.sort(" instead.
    WARNING: deprecated syntax "/ (" at /home/sayed/.julia/v0.4/PDMats/src/generics.jl:26. Use "/(" instead.

and the nail in the coffin:

    ERROR: LoadError: Cairo must be installed to use the PNG backend.
     in PNG at /home/sayed/.julia/v0.4/Compose/src/Compose.jl:137
     in include at ./boot.jl:254
     in include_from_node1 at loading.jl:133
     in process_options at ./client.jl:306
     in _start at ./client.jl:406
    while loading /test.jl, in expression starting on line 5

Both "Cairo" and "Gadfly" are installed and running

    Pkg.status("Gadfly")
    Pkg.status("Cairo")
returns:

     - Gadfly                        0.3.13
     - Cairo                         0.2.28
as expected.

The warnings and the error might not be exactly related, because if I don't call the `draw` function I won't get that LoadError. However, because they both happened at the same time I suspect they are caused by the same issue.

I'm running Julia on Ubuntu 15.04:

    Version 0.4.0-dev+5933 (2015-07-12 17:39 UTC)
    Commit b2528a6* (2 days old master)
    x86_64-linux-gnu

**Comment by dcjones** [comment]
Are you able to load Cairo, with just `using Cairo`?

> ...I get a million warnings.

This is pretty much a cost of doing business on unstable versions of julia, and is probably unrelated.

**Comment by CNOT** [comment]
no Cairo is not loading. It gives another loading error:

    ERROR: LoadError: could not open file /home/sayed/.julia/v0.4/Cairo/src/../deps/deps.jl
     in include at ./boot.jl:254
     in include_from_node1 at ./loading.jl:133
     in include at ./boot.jl:254
     in include_from_node1 at ./loading.jl:133
     in reload_path at ./loading.jl:157
     in _require at ./loading.jl:69
     in require at ./loading.jl:52
    while loading /home/sayed/.julia/v0.4/Cairo/src/Cairo.jl, in expression starting on line 5
So you're suggesting that the issue is likely to be within Julia itself, rather than Gadfly?

**Comment by dcjones** [comment]
It seems there's an issue loading the Cairo package, not necessarily a Julia or Gadfly issue.

What happens if you run `Pkg.build("Cairo")`?

**Comment by CNOT** [comment]
OK, so running `Pkg.build("Cairo")` gave me couple of warnings:

    WARNING: beginswith is deprecated, use startswith instead.
but no errors. Now `using Cairo` doesn't return any errors, which is a good sign. Running the initial code, I still get those warnings and it takes super long; however it exits without hard errors and produces the plot.

**Comment by dcjones** [comment]
Ok, great! The warnings are just nagging me and other package developers to accommodate recent minor syntax changes. That happens on unstable from time to time and will get fixed. Taking super long to load/run is also a known issue that will improve when package precompilation in merged in 0.4.

**Comment by CNOT** [comment]
Thanks.
