### ISSUE TITLE
Geom.bar fails if Scale.y_log10 and small y values

### ISSUE THREAD

**Issue by montyvesselinov** [dcjones/Gadfly.jl#650]
eigenv=[10^-4.1,10^-3.2]
plot(x=1:2, y=eigenv, Scale.x_discrete, Scale.y_log10, Geom.bar)

produces nada

**Comment by dcjones** [comment]
Fixed in master:

<img width="626" alt="screen shot 2015-09-16 at 9 25 26 pm" src="https://cloud.githubusercontent.com/assets/210361/9924945/7f68b196-5cb9-11e5-9092-29d1a96fb5d1.png">
