### ISSUE TITLE
Multi-plotting or sub-plotting with Gadfly

### ISSUE THREAD

**Issue by m-legrand** [dcjones/Gadfly.jl#656]
I am a big fan of Julia used along with Gadfly on notebooks to make friendly presentations of my work. Unfortunately, I didn't manage to include home-made plotting functions into blocks, subplot style. For instance, let's say I have written a function `netplot(A,C)`, where `A` is an adjacency matrix and `C` a vector of `A`'s nodes subsets (my clusters), which uses Gadfly to plot the correspondant network, with vertices colored according to their cluster. What I want to do is : 
- in a very basic way, being able have `netplot(A,C1)`, `netplot(A,C2)` and `netplot(A,C3)` side by side as a common cell output in an IJulia Notebook
- more generally being able to display them in a very configurable way (for example a big `netplot(A,C1)` on the left, and smaller `netplot(A,C2)` and `netplot(A,C3)` in a column on the right).

The only approaching solution I found on the documentation was [subplot_grid][subplot_grid] but it wasn't helping, eventually.

**EDIT** : What I am doing now, which is not very handy to visually compare clustering methods. The entire code can be found [there][ucb15].

<img width="677" alt="capture d ecran 2015-08-05 a 17 02 02" src="https://cloud.githubusercontent.com/assets/9072763/9100832/26226564-3b94-11e5-88df-bc0c299de0b0.png">

[subplot_grid]: http://dcjones.github.io/Gadfly.jl/geom_subplot_grid.html "Documentation on Gadfly/subplot_grid"
[ucb15]: http://maximelegrand.fr/gitlist/UC_Berkeley_2015/ "Source code"

**Comment by dcjones** [comment]
Have you tried `hstack` and `vstack`? You cat but plots side by side like
```julia
pl1 = plot(x=rand(10), y=rand(10), Geom.point)
pl2 = plot(x=rand(10), y=rand(10), Geom.point)
hstack(pl1, pl2)
```

**Comment by m-legrand** [comment]
`hstack` and `vstack` functions seem to have escaped my attention. It works great, thank you again for you amazing work.

<img width="922" alt="capture d ecran 2015-08-06 a 13 20 09" src="https://cloud.githubusercontent.com/assets/9072763/9122443/ecccdcf4-3c3d-11e5-8695-9edb949e5312.png">

**Comment by m-legrand** [comment]
Is there any way to control the size of each of the graphs, eventually with `Compose.jl`, `gridstack` ... ? For instance, if I want to plot side by side : 
* a 16cm x 8cm function plot;
* a 8cm x 8cm network plot.

**Comment by m-legrand** [comment]
Is there any way to control the size of each of the graphs, eventually with `Compose.jl`, `gridstack` ... ? For instance, if I want to plot side by side : 
* a 16cm x 8cm function plot;
* a 8cm x 8cm network plot.

**Comment by dcjones** [comment]
You can do this with some Compose tricks:

```julia
pl = hstack(compose(context(0, 0, 16cm, 8cm), render(pl1)),
            compose(context(0, 0, 8cm, 8cm), render(pl2)))
```

`render` turns the `Plot` into a Compose `Context`. Then we put that context in another context with a fixed size. You can also do this with relative sizes then draw it at 24cm by 8cm which may make things easier, like:

```julia
pl = hstack(compose(context(0, 0, 2/3, 1.0), render(pl1)),
            compose(context(0, 0, 1/3, 1.0), render(pl2)))
```

**Comment by m-legrand** [comment]
It indeed does the trick, I didn't think of using `compose` that way.
Perfect !
