### ISSUE TITLE
use auto-precompile in 0.4

### ISSUE THREAD

**Issue by stevengj** [dcjones/Gadfly.jl#657]
Assuming Gadfly (and any modules it requires) supports precompiling (which I think it does since people have been putting it in userimg for a long time), just add `VERSION >= v"0.4.0-dev+6521" && __precompile__()` to the top of `Gadfly.jl`.

**Comment by dcjones** [comment]
Done.

**Comment by vchuravy** [comment]
:tada: :fireworks: :+1:
