### ISSUE TITLE
Geom.step with color argument produces BoundsError()

### ISSUE THREAD

**Issue by kkmann** [dcjones/Gadfly.jl#665]
Hey,

I just encountered this:

    x = 1:10
    df1 = DataFrame(x=x, y=2x, label="double")
    df2 = DataFrame(x=x, y=x.^2, label="square")
    df3 = DataFrame(x=x, y=1./x, label="inverse")

    df = vcat(df1, df2, df3)

    plot(df, x="x", y="y", color="label", Geom.step,
    Scale.color_discrete_manual("blue","red", "green"))

works perfectly fine with Geom.line instead.

**Comment by dcjones** [comment]
This is fixed in master now. See #612.
