### ISSUE TITLE
UndefVarError: _checkbounds not defined

### ISSUE THREAD

**Issue by CNOT** [dcjones/Gadfly.jl#670]
When I try to use Gadfly; ignoring the warnings about `require` being deprecated, I'm getting the following error:

    using Gadfly
    ERROR: LoadError: LoadError: LoadError: UndefVarError: _checkbounds not defined
     in include at ./boot.jl:259
     in include_from_node1 at ./loading.jl:271
     in include at ./boot.jl:259
     in include_from_node1 at ./loading.jl:271
     in require at ./loading.jl:210
     in include at ./boot.jl:259
     in include_from_node1 at ./loading.jl:271
     in require at ./loading.jl:210
    while loading /PATH/TO/.julia/v0.4/DataArrays/src/indexing.jl, in expression starting on line 103
    while loading /PATH/TO/.julia/v0.4/DataArrays/src/DataArrays.jl, in expression starting on line 61
    while loading /PATH/TO/.julia/v0.4/Gadfly/src/Gadfly.jl, in expression starting on line 7

There are similarities with issue #647 , but I think this is a totally different error.
I'm running Julia `0.4.0-pre+7102` on Ubuntu.

**Comment by IainNZ** [comment]
This is a DataArrays problem on Julia 0.4. I think its fixed:
https://github.com/JuliaStats/DataArrays.jl/commit/d24f21eaaa85a6e99982bf0637ca96eba043feb4
so you should `Pkg.checkout("DataArrays")` or use Julia 0.3

**Comment by CNOT** [comment]
You are right. the issue resolved after updating the packages. Thanks.
