### ISSUE TITLE
Turning off ticks, labels, guides

### ISSUE THREAD

**Issue by timholy** [dcjones/Gadfly.jl#675]
I'm trying to replicate an interactive element like this one: https://github.com/timholy/ImageView.jl/blob/master/readme_images/contrast.jpg

It's a histogram where the number of pixels is presumably irrelevant, and so I'd like to suppress rendering of y-ticks and the y-axis label. I poked around a little while, and by setting `plot_aes` fields like
```jl
plot_aes.ytick = Float64[]
plot_aes.ytickvisible = Float64[]
plot_aes.ytickscale = Float64[]
```
I could suppress the ticks. However, I suspect I just failed to find a simple method like `Guide.xticks(visible=false)`. Any tips?

I'd be interested more generally in issues like "how do I get rid of guides?" "How do I suppress the axis label"?

Brief answers are fine; I'm happy to try to expand them & contribute to the documentation.

**Comment by timholy** [comment]
I should add that I also tried this:
```jl
julia> p = Gadfly.plot(x=v, Gadfly.Geom.histogram, Gadfly.Stat.yticks(ticks=[]))
Error showing value of type Gadfly.Plot:
ERROR: MethodError: `zero` has no method matching zero(::Type{Any})
 in render_colorless_bar at /home/tim/.julia/v0.4/Gadfly/src/geom/bar.jl:68
 in render at /home/tim/.julia/v0.4/Gadfly/src/geom/bar.jl:323
 in render at /home/tim/.julia/v0.4/Gadfly/src/geometry.jl:38
 in render_prepared at /home/tim/.julia/v0.4/Gadfly/src/Gadfly.jl:847
 in render at /home/tim/.julia/v0.4/Gadfly/src/Gadfly.jl:787
 in display at /home/tim/.julia/v0.4/Gadfly/src/Gadfly.jl:1038
 in display at /home/tim/.julia/v0.4/Gadfly/src/Gadfly.jl:151
 in print_response at REPL.jl:135
 in print_response at REPL.jl:122
 in anonymous at REPL.jl:624
 in run_interface at ./LineEdit.jl:1610
 in run_frontend at ./REPL.jl:863
 in run_repl at ./REPL.jl:167
 in _start at ./client.jl:453
```
and that saying `ticks=Float64[]` doesn't change the error.

In general I wonder whether using `nothing` to signal "automatic" is the right choice; perhaps Gadfly should define and export `automatic`, and reserve `nothing` for "omit"?

**Comment by dcjones** [comment]
I think I need a general mechanism for suppressing default guides. I'm thinking now that the set of default guides should be kept in `Theme`. Then you could just pass `Theme(guides=nothing)`.

**Comment by timholy** [comment]
In this case I like the x-ticks, I just don't want the y-ticks.

**Comment by dcjones** [comment]
Ok, there are only a few default guides so that would be more trouble than it's worth perhaps. I added a `Guide.xticks(ticks=nothing)` option to completely disable x or y ticks (`:auto` does the default automatic ticks). It could also do with more fine grained control, like just turning off the grid lines or just the labels, which could be handled by adding options to `Guide.x/yticks`.

**Comment by timholy** [comment]
Just tested this, and it works a treat. Many thanks! Thanks for also doing the docs.

Funny story: I first asked Mathworks for a plotting tweak, the ability to suppress drawing the y-axis-line, back around 2002. Last I checked, it still wasn't possible. Here, I ask a simple question and get a fix in < 24hrs.
