### ISSUE TITLE
LoadError: error in method definition: function Base.sum must be explicitly imported to be extended

### ISSUE THREAD

**Issue by cndesantana** [dcjones/Gadfly.jl#684]
I just installed Gadfly using Pkg.clone("https://github.com/dcjones/Gadfly.jl.git") and Pkg.build("Gadfly") and I am not able to use it. When I call a simple "using Gadfly" I get the following (long) error message. 

I am running Julia Version 0.4.0-dev+5920 in a Ubuntu 14.04 machine

julia> using Gadfly
ERROR: LoadError: LoadError: LoadError: LoadError: LoadError: LoadError: LoadError: error in method definition: function Base.sum must be explicitly imported to be extended
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:133
 in reload_path at ./loading.jl:157
 in _require at ./loading.jl:69
 in require at ./loading.jl:55
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:133
 in reload_path at ./loading.jl:157
 in _require at ./loading.jl:69
 in require at ./loading.jl:55
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:133
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:133
 in reload_path at ./loading.jl:157
 in _require at ./loading.jl:69
 in require at ./loading.jl:55
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:133
 in reload_path at ./loading.jl:157
 in _require at ./loading.jl:69
 in require at ./loading.jl:55
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:133
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:133
 in reload_path at ./loading.jl:157
 in _require at ./loading.jl:69
 in require at ./loading.jl:52
while loading /home/cdesantana/.julia/v0.4/NaNMath/src/NaNMath.jl, in expression starting on line 70
while loading /home/cdesantana/.julia/v0.4/DualNumbers/src/DualNumbers.jl, in expression starting on line 4
while loading /home/cdesantana/.julia/v0.4/Optim/src/autodiff.jl, in expression starting on line 1
while loading /home/cdesantana/.julia/v0.4/Optim/src/Optim.jl, in expression starting on line 22
while loading /home/cdesantana/.julia/v0.4/KernelDensity/src/KernelDensity.jl, in expression starting on line 5
while loading /home/cdesantana/.julia/v0.4/Gadfly/src/statistics.jl, in expression starting on line 16
while loading /home/cdesantana/.julia/v0.4/Gadfly/src/Gadfly.jl, in expression starting on line 1088

**Comment by dcjones** [comment]
It seems to be an error loading the NaNMath.jl package. I'm not sure why it's occurring, but I'd recommend updating your julia 0.4 install to a newer revision and trying again.

**Comment by cndesantana** [comment]
Thanks for your suggestion! I will do it soon and let you know about it.

**Comment by cndesantana** [comment]
Hi again, 

I just installed the new stable 0.4 release of julia (Version 0.4.0-rc1+7 (2015-09-10 20:01 UTC)
). Indeed I was able to use Gadfly, thanks! :)

But now I was not able to plot anything else. I will open a new issue about this new problem. 

Thanks for your attention!
