### ISSUE TITLE
Boxplot not reordering plots

### ISSUE THREAD

**Issue by guitar58** [dcjones/Gadfly.jl#690]
Hello,

I have a dataframe:
Groups    Score
A              1
B              2
C              3

That I want to use for regression and boxplots (using gadfly).

I reordered my categorical variables using:

pool!(df2, [:Group])

df2[:Group] = PooledDataArray(df2[:Group], UTF8String["A", "C", "B"])

Now my regression output shows the coefficients in the order that I want.
However, using gadfly:

p1= plot(df2, x="Group", y="Score", Geom.boxplot,
Guide.ylabel("Scores"), # label for y-axis
Guide.title("Scores by Groups"))

The groups are still ordered alphabetically and not according to my reorder.

It would be useful to have Gadfly keep the order that I already instituted for the categorical variable.

Thanks.

**Comment by amellnik** [comment]
Could you provide a stand-alone code snippet that reproduces the problem by any chance?  I was unable to get the above to run and I might be missing something.  

Are you pooling your data just to reorder it?  Plot with Geom.boxplot preserves the order in which the categorical variable appears, so you can just reorder the dataframe:

```julia
df2 = DataFrame(Group = ["A", "B", "C"], Score = [1,2,3])
p1= plot(df2, x="Group", y="Score", Geom.boxplot)
```
![image](https://cloud.githubusercontent.com/assets/7132414/9892379/1532c8e4-5bc3-11e5-8e6c-a63ed8b40e75.png)
```julia
#This is a terrible way to reorder
df3 = DataFrame(Group=ASCIIString[], Score=Int64[])
for gr in ["A", "C", "B"] 
    append!(df3, df2[df2[:Group].==gr,:])
end
p1= plot(df3, x="Group", y="Score", Geom.boxplot)
```
![image](https://cloud.githubusercontent.com/assets/7132414/9892388/2bafc90a-5bc3-11e5-8a6b-f04006f2a918.png)

**Comment by guitar58** [comment]
Alex,

Here's my entire code:

using DataFrames
using GLM
using Distributions
using NumericExtensions
using Gadfly
using Cairo
#load modules

df = readtable("~\ipython-test\MIF-IC6.csv", header=true)
#read entire database

df2 = df[(df[:Group] .== "Control") |(df[:Group] .== "UTI") |(df[:Group] .== "Radiation"), :]
#select 3 groups only

pool!(df2, [:Group])
#need to do this to make sure that julia sees it as categorical

df2[:Group] = PooledDataArray(df2[:Group], UTF8String["Control", "UTI", "Radiation"])
#reorder Group levels

levels(df2[:Group])
#to check they are listed in correct order

lm1 = fit(LinearModel, MIF_pg_ml ~ Group, df2)
#run linear regression; coefficients are planned t-test comparisons

p1= plot(df2, x=PooledDataArray(df2[:Group], UTF8String["Control", "UTI", "Radiation"]), y="MIF_pg_ml", Geom.boxplot,
Guide.ylabel("MIF(pg/ml)"), # label for y-axis
Guide.title("Urine MIF concentrations"))
#to create graph - order is still alphabetical

I am trying to reorder the dataframe (and I can do this quite easily in R). Was told that PooledDataArray was the way to go and it does work for the regression but not for the boxplots. Ideally, I would like to do it just once and not reorder again just for the graphs, however, I'm just learning Julia.

Thanks for the help.

Pedro

**Comment by dcjones** [comment]
It won't respect the order of the pool in a `PooledDataArray` (which is what R does, so it's a reasonable assumption), but like @amellnik pointed it out, it does respect order the values appear in a vector. You can reorder the rows of the data frame, but it should also work if you pass `Scale.x_discrete(levels=UTF8String["Control", "UTI", "Radiation"])` to `plot`, where `levels` are in the order you'd like.

**Comment by guitar58** [comment]
That works great!
Thanks for your help.

**Comment by dcjones** [comment]
Sure, no problem.
