### ISSUE TITLE
Better bar widths for unevenly-spaced data (already done for boxplot)

### ISSUE THREAD

**Issue by amellnik** [dcjones/Gadfly.jl#692]
Could something similar to 2246a737ecf825ac5794b55bf8c758a5af4b2094 be done for Geom.bar?  This was first raised in #596 and done for boxplot.  A simple example to produce the issue is 

```julia
df = DataFrame(Year = [1999,2001,2002,1999,2002], 
Customer = ["Marvel", "Marvel", "Marvel", "DC", "DC"],
Number = [12,33,1,23,26])
plot(df, Geom.bar, x="Year", y="Number", color="Customer")
```
![image](https://cloud.githubusercontent.com/assets/7132414/9890445/c8ef1d7e-5bb4-11e5-8c9a-ddb46b862b28.png)

**Comment by dcjones** [comment]
Should be better now.
