### ISSUE TITLE
How to get Gadfly clean?

### ISSUE THREAD

**Issue by harmeling** [dcjones/Gadfly.jl#697]
Trying `using Gadfly` I get warned:

    WARNING: Color is deprecated, please use Colors instead. See       
    https://github.com/JuliaGraphics/Colors.jl

Looks like my Gadfly might be outdated?  So running `Pkg.status()` shows for Gadfly:

     - Gadfly                        0.3.9              da1669b8 (dirty)

Looks like that version of `Gadfly` still uses the `Color` package and I guess it should use `Colors`?

Question: how do I upgrade to the current version of `Gadfly`?  

What I tried:

    julia> Pkg.update()
    INFO: Updating METADATA...
    INFO: Updating Mocha...
    INFO: Updating Ipopt...   
    INFO: Computing changes...
    INFO: Installing Color v0.4.8

    julia> Pkg.rm("Gadfly")
    INFO: No packages to install, update or remove
    INFO: Package database updated

    julia> Pkg.add("Gadfly")
    INFO: No packages to install, update or remove
    INFO: Package database updated
    INFO: METADATA is out-of-date — you may not have the latest version of Gadfly
    INFO: Use `Pkg.update()` to get the latest versions of your packages

Strange, why does it suggest to `Pkg.update()` again? Also `Pkg.status()` still shows that `Gadfly` is still 0.3.9 and dirty.

I am running `julia` on a Mac OS 10.10.3:

    julia> versioninfo()
    Julia Version 0.3.11
    Commit 483dbf5* (2015-07-27 06:18 UTC)
    Platform Info:
      System: Darwin (x86_64-apple-darwin13.4.0)
      CPU: Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
      WORD_SIZE: 64
      BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
      LAPACK: libopenblas
      LIBM: libopenlibm
      LLVM: libLLVM-3.3

Any suggestion?  Thanks!

**Comment by dcjones** [comment]
The `dirty` means you've made changes to one or more of the files in Gadfly. If you go to the Gadfly directory (usually `~/.julia/v0.3/Gadfly`) and run `git stash`, or if you're sure you don't need the changes `git reset --hard`, it should be resolved.

**Comment by harmeling** [comment]
Thanks a lot!  Now it works again!
