### ISSUE TITLE
Bug: plot bounds with discrete axis

### ISSUE THREAD

**Issue by Godisemo** [dcjones/Gadfly.jl#709]
Best explained by the pictures below. I did git bisect and figured out that the bug was introduced in e061d458c3d7725dd69566745717fb0ed1bdb47e.

Before e061d458c3d7725dd69566745717fb0ed1bdb47e:
![good](https://cloud.githubusercontent.com/assets/847898/10132014/6ded485e-65d4-11e5-99ad-ec404f27b169.png)
After e061d458c3d7725dd69566745717fb0ed1bdb47e:
![bad](https://cloud.githubusercontent.com/assets/847898/10132013/6dc32c72-65d4-11e5-8ea9-b077620d762f.png)

**Comment by dcjones** [comment]
Thanks, I clearly didn't think that one through.
