### ISSUE TITLE
MethodError when using either Ascii or Unicode string with text in Guide.annotation

### ISSUE THREAD

**Issue by protogeezer** [dcjones/Gadfly.jl#711]
the example below results in:
ERROR: MethodError: `text` has no method matching text(::UTF8String)
or
ERROR: MethodError: `text` has no method matching text(::ASCIIString)
in 0.4.0 rc3
======
using Gadfly, DataFrames, Compose
x = [-2.664, 53.570]
sl = 2*randn(2_000);
inter = 10*randn(2_000)+50;
df_scatter = DataFrame(slope=sl, intercept=inter);
#MethodError with either string or a literal string
str1 = @sprintf("equation: %6.3f⋅X + %6.3f",x[2],x[1])
#str1 = @sprintf("equation: %6.3fX + %6.3f",x[2],x[1])
plot( layer(df_scatter,y="intercept",x="slope",Geom.histogram2d),
			layer(x=[-10,10],y=[85,25],Geom.line),
			Guide.annotation(compose(context(),text(x=2,y=96,str1))),
			Guide.annotation(compose(context(),text(x=2,y=91,"constraint: R<sup>2</sup> > 0.5"))))

**Comment by dcjones** [comment]
The error here is that `text` doesn't take keyword arguments. It should work with `text(2,96,str1)` and `text(2,91,"constraint: R2 > 0.5")`.
