### ISSUE TITLE
Can't load Gadfly julia 0.3.11

### ISSUE THREAD

**Issue by jdhare** [dcjones/Gadfly.jl#715]
New install of Julia: Version 0.3.11 (2015-07-27 06:18 UTC) Official http://julialang.org/ release x86_64-apple-darwin13.4.0

Added Gadfly with Pkg.add("Gadfly")
Load Gadfly with using Gadfly

Output is:

ERROR: LOAD_CACHE_PATH not defined
 in include at /Applications/Julia-0.3.11.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.11.app/Contents/Resources/julia/lib/julia/sys.dylib
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:54
 in include at /Applications/Julia-0.3.11.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.11.app/Contents/Resources/julia/lib/julia/sys.dylib
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
while loading /Users/jdhare/.julia/v0.3/Compose/src/Compose.jl, in expression starting on line 148
while loading /Users/jdhare/.julia/v0.3/Gadfly/src/Gadfly.jl, in expression starting on line 9

**Comment by aviks** [comment]
Same as https://github.com/dcjones/Compose.jl/issues/160

**Comment by edniemeyer** [comment]
Had the same issue. Solved it by adding the package "Cairo"

**Comment by dcjones** [comment]
Fixed now in Compose 0.3.17.
