### ISSUE TITLE
Gadfly no longer respects x_continous min/maxvalue if data is outside bounds

### ISSUE THREAD

**Issue by Keno** [dcjones/Gadfly.jl#716]
Compare
<img width="811" alt="screen shot 2015-10-05 at 10 43 44 pm" src="https://cloud.githubusercontent.com/assets/1291671/10298981/dbe4a454-6bb2-11e5-8793-90ab376de3f6.png">
<img width="962" alt="screen shot 2015-10-05 at 10 44 02 pm" src="https://cloud.githubusercontent.com/assets/1291671/10298980/dbe1943a-6bb2-11e5-9b2e-84f89915a3d7.png">

**Comment by dcjones** [comment]
This behavior was changed at some point. How it works now is that `Coord.cartesian(xmin=5, xmax=10)` will give hard limits like the above plot, and `Scale.x_continuous(minvalue=5, maxvalue=10)` gives soft limits like the below plot.

This is kind of opaque, but previously these were two things that did almost the same thing, so I thought it would be useful to differentiate.

**Comment by Keno** [comment]
Thanks. Maybe update the documentation?
