### ISSUE TITLE
MWE for 718

### ISSUE THREAD

**Issue by protogeezer** [dcjones/Gadfly.jl#719]
using DataFrames,Gadfly,Colors

function test()
	df = readtable("test_df.csv");
	slope_act = df[:slopes];
	y_inter_act = df[:intercepts];
	x = hcat(y_inter_act,slope_act)';
	e1,e2,counts = hist2d(x',collect(0:1:100),collect(-10:.2:10));
	# produces 24
	maximum(counts)
	p1 = plot(layer(y=slope_act,x=y_inter_act,Geom.histogram2d(xbincount=100,ybincount=100)),
						Guide.title("slopes vs intercepts from Geom.histogram2d"),
						Guide.xticks(ticks=[0,25,50,75,100]),Guide.yticks(ticks=[-10,-5, 0, 5,10]),
						Theme(panel_fill=RGB(.5,.5,.5)));
	draw(PDF("example1.pdf",6inch,4inch),p1);
	x_range_small = collect(0:1:100);
	y_range_small = collect(-10:.2:10);
	e1,e2,counts = hist2d(x',x_range_small,x_range_small);
	mids_x = collect(0.5:1:99.5);
	mids_y = collect(-9.9:.2:9.9);
	intercepts = reshape(repmat(mids_x,1,100),10000);
	slopes = reshape(repmat(mids_y,1,100)',10000);
	max_v = floor(maximum(counts)/2);
	e1,e2,counts = hist2d(x',x_range_small,y_range_small);
	counts = reshape(counts,10000);
	p2 = plot(layer(x=intercepts,y=slopes,color=counts,Geom.rectbin),
						Guide.title("slopes vs intercepts from Geom.rectbin"),
						Guide.xticks(ticks=[0,25,50,75,100]),Guide.yticks(ticks=[-10,-5, 0, 5,10]));
	draw(PDF("example2.pdf",6inch,4inch),p2);
	non_zero = counts.!=0;
	intercepts = intercepts[non_zero];
	slopes = slopes[non_zero];
	counts = counts[non_zero];
	p3 = plot(layer(x=intercepts,y=slopes,color=counts,Geom.rectbin),
						Guide.title("slopes vs intercepts from Geom.rectbin - zero counts removed"),
						Guide.xticks(ticks=[0,25,50,75,100]),Guide.yticks(ticks=[-10,-5, 0, 5,10]));
	draw(PDF("example3.pdf",6inch,4inch),p3);
end

**Comment by tbreloff** [comment]
Can you:

- put this in #718 where it belongs
- wrap the code with triple-backticks and indent properly... this is unreadable

**Comment by protogeezer** [comment]
Ok, that worked. 

Do you have any advice as to how to get the data frame that instigates the apparent problems better and more clearly than any random data I was able to muster uploaded in the issue? 

Cut and past into a comment didn’t seem practical - since it’s almost 8K pairs of points.

I tried renaming the .csv to .txt, zipping it and changing the suffix, etc.

Stephen

**Comment by dcjones** [comment]
Closed in favor of #718. Thanks for the example, that made it easy.

**Comment by protogeezer** [comment]
Glad it helped. 

Is there a more githubbish way to provide data files - the only thing that seemed even remotely possible was to submit a pull request with just the data file? I can’t imagine how often this will be important but it seems like if there is a way to do it, it would be great to know about it ahead of time.

Stephen

**Comment by dcjones** [comment]
You can post individual files on [gist](https://gist.github.com/), which is probably the most githubbish way to do that. I don't mind having it emailed to me either. That makes it harder for anyone else to fix it, but it's generally me who needs to fix these sorts of things anyway.
