### ISSUE TITLE
Contour plot with line layer

### ISSUE THREAD

**Issue by bdeonovic** [dcjones/Gadfly.jl#732]
I have the following contour plot (samples from posterior using MCMC):
```julia
plot(x=mx, y=my, z=tot,
                Geom.contour,
                Guide.xlabel(c.names[combs[i][1]], orientation=:horizontal),
                Guide.ylabel(c.names[combs[i][2]], orientation=:vertical),
                Guide.title("Contour of $(c.names[combs[i][1]]) vs $(c.names[combs[i][2]])")
                )
```
![contournolines-1](https://cloud.githubusercontent.com/assets/805168/10704416/3ecf2d0e-799c-11e5-8197-021f71d84513.png)
but when I try to add a layer of lines (the path the MCMC sampler took) the countour plots suddenly get very small. 
```julia
plot(layer(x=x, y=y, Geom.line),
		layer(x=mx, y=my, z=tot,
                Geom.contour),
                Guide.xlabel(c.names[combs[i][1]], orientation=:horizontal),
                Guide.ylabel(c.names[combs[i][2]], orientation=:vertical),
                Guide.title("Contour of $(c.names[combs[i][1]]) vs $(c.names[combs[i][2]])")
                )
```
![contour-1](https://cloud.githubusercontent.com/assets/805168/10704480/b71cb5b0-799c-11e5-8550-2cbadf860761.png)

Is this supposed to happen? What is happening? Sorry I don't have a reproducible example.

**Comment by tbreloff** [comment]
What are x/y? If you plot the line by itself, is the axis correct?

**Comment by bdeonovic** [comment]
Yes the line plot looks just fine when it is plotted by itself (it looks just like it does with the contour plot), its just the contour plot that gets scaled down for some reason.

**Comment by bdeonovic** [comment]
Ah wait nevermind, you are right, the contour plots are more zoomed in.
