### ISSUE TITLE
Feature request: logarithmic (continuous) color scale

### ISSUE THREAD

**Issue by simleb** [dcjones/Gadfly.jl#744]
A logarithmic continuous color scale would be nice to have.

Consistently with `Scale.x_continuous` and `Scale.y_continuous`, a number of transformed continuous scales could be provided:
* `Scale.color_continuous` (scale without any transformation).
* `Scale.color_log10`
* `Scale.color_log2`
* `Scale.color_log`
* `Scale.color_asinh`
* `Scale.color_sqrt`

**Comment by durcan** [comment]
I brought up some trouble I was having implementing exactly this functionality in #573. I agree that colors currently are in need of some attention, both in scalings as well as optional, built-in colormaps.

**Comment by tbreloff** [comment]
It doesn't directly solve your request, but here's how you could customize using Plots.jl:

```
julia> using Plots, RDatasets; gadfly();

julia> d = dataset("ggplot2", "diamonds");

julia> hexbin(d, :Price, :Carat,
              nbins=70,
              size=(500,500),
              c=colorscheme(:heat, [0,0.01,1]),
              bg=:black)

julia> png("/home/tom/tmp")
```

![tmp](https://cloud.githubusercontent.com/assets/933338/11224349/90219fe8-8d42-11e5-86f7-50fa479d47dd.png)

One caveat is that you'll need to do a `Pkg.checkout("Plots")` for it to work properly, as I've recently fixed a bug.
