### ISSUE TITLE
Can anyone else rebuild and upload the docs?

### ISSUE THREAD

**Issue by amellnik** [dcjones/Gadfly.jl#789]
I realized that there's a lot of tickets related to the fact that there are many changes in the docs which do not appear on gadflyjl.org.  One example is [Coord.cartesian](https://github.com/dcjones/Gadfly.jl/blob/master/doc/coord_cartesian.md) which appears to resolve https://github.com/dcjones/Gadfly.jl/issues/784, https://github.com/dcjones/Gadfly.jl/issues/773, https://github.com/dcjones/Gadfly.jl/issues/668, and possibly https://github.com/dcjones/Gadfly.jl/issues/633.  It was fixed by @dcjones in https://github.com/dcjones/Gadfly.jl/commit/639c885ad0224d504e3d221bd5fb44b8fff83637 and commited in https://github.com/dcjones/Gadfly.jl/commit/79e265073e94cd022427716442e72fa82654d591 on October 5th.  Similarly, I think https://github.com/dcjones/Gadfly.jl/issues/760 just needs the docs to be rebuilt.  However, the documentation web site looks like it hasn't been built in quite a while. 

Is there anyone, perhaps @timholy, who can both rebuild the docs (Judo doesn't work on a Windows host) and upload it to gadflyjl.org if @dcjones is not around?

**Comment by amellnik** [comment]
I was able to rebuild the docs with https://github.com/dcjones/Gadfly.jl/pull/796 and https://github.com/dcjones/Judo.jl/pull/23.  I've attached the result.  If no one is available who has access to gadflyjl.org (perhaps @darwindarak?) I can make a temporary mirror with the updated docs on one of my sites.


[html.zip](https://github.com/dcjones/Gadfly.jl/files/101290/html.zip)

**Comment by darwindarak** [comment]
I have no idea where the docs are hosted. Maybe until @dcjones has more time, we can use Github pages to host the docs.

If there are no objections, I'll go ahead an push the updates to `gh-pages` in a couple of days.

**Comment by simleb** [comment]
They are hosted on a server named `badfigure` if that helps… as can be seen [here][1]. 

[1]: https://github.com/dcjones/Gadfly.jl/blob/master/doc/mkfile

**Comment by darwindarak** [comment]
I've updated the docs on the `gh-pages` branch.  For now, we can use https://dcjones.github.io/Gadfly.jl

**Comment by tlnagy** [comment]
Ref #879
