### ISSUE TITLE
Simple setting of color in plot()

### ISSUE THREAD

**Issue by Vgrunert** [dcjones/Gadfly.jl#795]
Hi,

I could not find out how to simply set the color of a plot to "green" for example. Am I missing one of the most obvious features or is it not present? 

What I wish to do is:

plot( x = rand(10), y=rand(10), color = "green", Geom.point )

I am aware that the color can be set to "green" via:

plot( x = rand(10), y=rand(10),  Theme(default_color = color("")) ),

which is rather inconvenient for such a standard task in plotting. Being able to set the color the one of the standard colors (black, blue, red, green, yellow, etc.) should in my opinion be a standard feature of any plotting library. 

If it should be present, please point out how to do it in the documentation, where I could not find it.

Thank you very much.

**Comment by tbreloff** [comment]
Not that I know of. If you want a convenient interface for plotting, may I recommend Plots.jl?

**Comment by tlnagy** [comment]
Check out the discussion in #818. I hope to add this as it would be much more convenient for quick and dirty plots.
