### ISSUE TITLE
Geom.point is invisible

### ISSUE THREAD

**Issue by ultradian** [dcjones/Gadfly.jl#797]
I am using Gadfly with Julia 0.4 on a Debian 8 machine that brings up a Konqueror version 4.14 window when plotting.  Plots made with Geom.line work fine, but when I use Geom.point the points don't show up.  If I plot both points and lines, only the lines show up.  Is this something in my setup or a bug?

**Comment by darwindarak** [comment]
Can you post some sample code that shows this problem?

**Comment by ultradian** [comment]
>plot(x=rand(10), y=rand(10))

shows up all the axes, x and y labels, gridlines, but no points
![gadflyplot1](https://cloud.githubusercontent.com/assets/14141325/12542252/5e41cebc-c2d5-11e5-8f51-b22e010b9dee.png)

>plot(x=rand(10), y=rand(10), Geom.point, Geom.line)

shows the line, but no points
![gadflyplot2](https://cloud.githubusercontent.com/assets/14141325/12542253/670f16ee-c2d5-11e5-9de3-aae9523759aa.png)

**Comment by ultradian** [comment]
As an addendum, I just tested this on my laptop which also runs Julia 0.4, Debian 8, but outputs to Iceweasel instead of Konqueror.  There, it works fine with the points. Any suggestions about how I could debug this?  Or even just change the browser Gadfly chooses to output to?

**Comment by loganwilliams** [comment]
I'm having a similar issue -- points are invisible in Safari but render correctly in Chrome, using Gadfly 0.4.2.

Julia Version 0.4.3
Commit a2f713d (2016-01-12 21:37 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

**Comment by timholy** [comment]
One alternative is [Immerse](https://github.com/JuliaGraphics/Immerse.jl), which plots in a Gtk window.

**Comment by ultradian** [comment]
Immerse works nicely.
`Gadfly.plot(x=rand(10), y=rand(10), Geom.point, Geom.line)
`
![gadflyplot3](https://cloud.githubusercontent.com/assets/14141325/13083099/71a1c7b8-d488-11e5-914f-b312ba2ab6a0.png)

although I still would like to figure out more about how the rendering is set up.

**Comment by timholy** [comment]
You can follow the breadcrumbs through
```jl
p = plot(...)
@which display(p)
```
This will lead you to some code which loops over potential display objects, and between the code you find and `using Base.Multimedia: displays xdisplayable` you should be able to follow it further.

**Comment by tlnagy** [comment]
@ultradian, are you still having this problem?

**Comment by ultradian** [comment]
Yes and No.  I just tried this with the new Firefox (45.3) and it seems to be working now.  When I go back to Konqueror (now version 4.14.2)  it doesn't work although it did back in February!  My guess is that it is browser specific failure to implement some type of rendering, but I can't track it down.  I put up a sample file at [gadfly-rendering] (https://github.com/ultradian/gadfly-rendering), if people want to pursue this more, but as this doesn't look like a Gadfly issue, I'm happy if we want to close it.  Especially since there is a Gtk alternative.
