### ISSUE TITLE
Error when using Gadfly

### ISSUE THREAD

**Issue by JonathanH5** [dcjones/Gadfly.jl#806]
Hi,

I tried to use your project, but when starting my program I get an error. The log file is appended.
I just try to execute these lines to verify everything is installed correctly:
`Pkg.add("Gadfly")
using Gadfly`

My operation system is Ubuntu 14.04 LTS run in a virtual machine (Parallels Desktop). Do you know the cause? It did not work using Juliabox.org, too.

Best,
Jonathan.
[log.txt](https://github.com/dcjones/Gadfly.jl/files/127901/log.txt)

**Comment by tbreloff** [comment]
Please update your Julia version. I see you're using v0.2. Current release is 0.4.3

**Comment by JonathanH5** [comment]
Thank you, this solved the Issue... .
