### ISSUE TITLE
Geom.line plot order seems odd.

### ISSUE THREAD

**Issue by RobertM314** [dcjones/Gadfly.jl#814]
Hello, and first, thanks for all your hard work.

I'm very new to the Julia/Gadfly/Juno ecosystem, I've been working in Ipython/numpy/matplotlib for some time, but I'm an engineering analysis person, not a software person.

I find this behaviour odd:
plot(x = [1,2,3], y = [1,3,2], Geom.line)
plot(x = [1,3,2], y = [1,2,3], Geom.line) 
produce the same plot.

I would expect the line to be drawn (1,1) > (2,3) > (3,2) in the first case, and (1,1) > (3,2) > (2,3) in the second, but both plots draw the same line. 
In a less trivial case, I would have expected a = linspace(0,2pi,50)
plot(x = cos(a), y = sin(a), Geom.line) to draw a circle, when the plot aspect ratio is correct. Instead the line appears to link the points in order of increasing x.
![circle](https://cloud.githubusercontent.com/assets/17785367/13781284/2a7dbc26-ea99-11e5-8337-7cf216425ad5.png)

I'm running Julia 0.4.2, Gadfly installed through the Julia Pkg.add(), Packages updated as of yesterday (20160314). 
Again, thanks for all your hard work.

**Comment by tbreloff** [comment]
You want Geom.path.  Geom.line will sort the data by x value.

**Comment by RobertM314** [comment]
Oops, palm-to-face.
Thanks
