### ISSUE TITLE
Shared title when stacking?

### ISSUE THREAD

**Issue by tlnagy** [dcjones/Gadfly.jl#821]
Is it possible to have one title when stacking plots using `hstack` and `vstack`? Because `Geom.title` associates with one plot vs the other:

```{.julia}
p = hstack(plot(sin, 0, 20, Guide.title("test")), plot(cos, 0, 20))
draw(PNG("test.png", 20cm, 8cm), p)
```
![test](https://cloud.githubusercontent.com/assets/1661487/14336797/64070e22-fc1c-11e5-86f1-81416b5a18bf.png)

**Comment by Mattriks** [comment]
See #600

**Comment by tlnagy** [comment]
Thanks I think that mostly fixes my problem.
