### ISSUE TITLE
Gadfly doesn't precompile due to libfontconfig

### ISSUE THREAD

**Issue by neilpanchal** [dcjones/Gadfly.jl#825]
I am on windows and I've come to the end of the internet searching how to install the fontconfig C library on windows. There isn't a simple way. 

From what I know, fontconfig is not a dependency...then why does Gadfly fail to compile the following erros:

![image](https://cloud.githubusercontent.com/assets/8161031/14545714/57cf19c6-0255-11e6-82a4-12eb717c9260.png)

**Comment by aviks** [comment]
Fontconfig is an optional dependency of Gadfly. Installing Gadfly does not automatically install Fontconfig. 

You should remove Fontconfig (`Pkg.rm("Fontconfig")` ) and then Gadfly will not try to load Pango or Fontconfig.

**Comment by fbanez** [comment]
I use Mac Os and I think I have the same problem. I am using Gadfly but, in order to save the plot in PNG format I need Fontconfig (at least, it is what it says). I have installed Fontconfig, but when I try to use it, it gives an error: 
ERROR: LoadError: error compiling __init__: could not load library "libfontconfig" ...

Do you know what am I doing wrong or what can I do?

Thanks!

**Comment by lobingera** [comment]
afaics, Fontconfig doesn't use BinDeps to resolve library paths and names. So you have installed libfontconfig in a place, but julia/ccall doesn't find it. Try to copy to the local folder.

**Comment by fbanez** [comment]
Sorry, how can I do that?
I installed Fontconfig in the same way I installed the other packages.

Thanks!

**Comment by lobingera** [comment]
julia needs to find the library (by name) to be able to dlopen and use it. 
```
julia> d = Libdl.dlopen(:libfontconfig)
Ptr{Void} @0x000000000277b7e0
```
would fail on your computer. There are path settings to find libraries, but the local dir should always be on the path. So you could find libfontconfig.dynlib (or similar) and copy to the local directory.

**Comment by fbanez** [comment]
Yo are right, I do not have libfontconfig.dynlib (or something similar) in the Julia path. I try to find it in my users path (.../.julia/v0.4/Fontconfig), but it is not there also.
Any idea?

Thanks for the help!

**Comment by grero** [comment]
I had the same problem and I ended up installing fontconfig via homebrew, i.e.

`brew install fontconfig`
 
in terminal.

**Comment by johnczito** [comment]
I've been having the same problem, and installing fontconfig via homebrew did the trick.

**Comment by tlnagy** [comment]
Running `Pkg.add("Cairo")` should install fontconfig and pango now.
