### ISSUE TITLE
using Gadfly fails

### ISSUE THREAD

**Issue by zboson** [dcjones/Gadfly.jl#828]
I installed Ubuntu 16.04 yesterday.  Then did

sudo apt-get install julia

then in Julia

    Pkg.add("Gadfly") 
    using Gadfly

reports

ERROR: LoadError: LoadError: error compiling anonymous: could not load library "libz"
libz: cannot open shared object file: No such file or directory
while loading /home/user/.julia/v0.4/GZip/src/zlib_h.jl, in expression starting on line 8
while loading /home/user/.julia/v0.4/GZip/src/GZip.jl, in expression starting on line 75
ERROR: LoadError: Failed to precompile GZip to /home/user/.julia/lib/v0.4/GZip.ji
while loading /home/user/.julia/v0.4/DataFrames/src/DataFrames.jl, in expression starting on line 15
ERROR: LoadError: Failed to precompile DataFrames to /home/user/.julia/lib/v0.4/DataFrames.ji
while loading /home/user/.julia/v0.4/Gadfly/src/Gadfly.jl, in expression starting on line 11
ERROR: Failed to precompile Gadfly to /home/user/.julia/lib/v0.4/Gadfly.ji
 in compilecache at ./loading.jl:400

zlib1g is installed. I tried

    sudo apt-get install zlib1g:i386

but it made no difference.

**Comment by tlnagy** [comment]
Did you try `Pkg.build("Gadfly")`?

**Comment by tlnagy** [comment]
Closing in favor of #829
