### ISSUE TITLE
Blocked when pkg.add("Gadfly")

### ISSUE THREAD

**Issue by memoiry** [dcjones/Gadfly.jl#830]
I have tried to pkg.add("Gadfly"), but there is no error and the output keeps like this..
Pkg.add("Gadfly")
INFO: Initializing package repository /Users/xuguodong/.julia/v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
INFO: Cloning cache of ArrayViews from git://github.com/JuliaLang/ArrayViews.jl.git
INFO: Cloning cache of Calculus from git://github.com/johnmyleswhite/Calculus.jl.git
INFO: Cloning cache of Codecs from git://github.com/dcjones/Codecs.jl.git
INFO: Cloning cache of ColorTypes from git://github.com/JuliaGraphics/ColorTypes.jl.git
INFO: Cloning cache of Colors from git://github.com/JuliaGraphics/Colors.jl.git
INFO: Cloning cache of Compat from git://github.com/JuliaLang/Compat.jl.git
INFO: Cloning cache of Compose from git://github.com/dcjones/Compose.jl.git
INFO: Cloning cache of Contour from git://github.com/tlycken/Contour.jl.git
INFO: Cloning cache of DataArrays from git://github.com/JuliaStats/DataArrays.jl.git
INFO: Cloning cache of DataFrames from git://github.com/JuliaStats/DataFrames.jl.git
INFO: Cloning cache of DataStructures from git://github.com/JuliaLang/DataStructures.jl.git
INFO: Cloning cache of Dates from git://github.com/quinnj/Dates.jl.git

it seems that something wrong with the cloning process, how can i fix it..? thx.

**Comment by daftmath** [comment]
Try opening a cmd window and navigating to your _**Julia-0.4.0\Git\bin**_ folder. Once you're there run the command **_git config --global url."https://".insteadOf git://_**

Then try to add the package again. It might take a long time so be patient.

**Comment by tlnagy** [comment]
In Julia v0.5+ you can use [`setprotocol!`](http://docs.julialang.org/en/latest/stdlib/pkg/?highlight=setprotocol#Base.Pkg.setprotocol!) to do this instead of changing your global git config.
