### ISSUE TITLE
Is the gadfly.org domain going away?

### ISSUE THREAD

**Issue by tbreloff** [dcjones/Gadfly.jl#832]
I just went to the docs and got a landing page as if there's no site:

```
This domain is registered at

This domain was recently registered at Namecheap. Please check back later!
```

**Comment by lobingera** [comment]
looks like http://dcjones.github.io/Gadfly.jl/ is existing and according to my browser history, is already in use for at least 3 months?

**Comment by tbreloff** [comment]
You're right.  The link from the readme goes there, but there's a link in the repo description which is what I normally click on.  Who can change that link?

![tmp](https://cloud.githubusercontent.com/assets/933338/14922414/78eba0a0-0e05-11e6-9f24-3afb855faa5c.png)

**Comment by lobingera** [comment]
i guess the owner of the repository?

**Comment by vchuravy** [comment]
Last time I was on gadflyjl.org was on April 17th, I guess this coincides with @dcjones being AWOL

**Comment by amellnik** [comment]
I changed the link in the readme a while back, but it looks like only @dcjones can change that description.

**Comment by vchuravy** [comment]
The website is also back.

**Comment by amellnik** [comment]
@vchuravy -- The web site is up, but the content there hasn't been regenerated in a long time.  The old documentation has lead to a few issues being opened: #789.

**Comment by tlnagy** [comment]
I might be able to get Daniel to point the website at github pages and then the http://gadfly.org domain will stay synced with the generated docs.

**Comment by simleb** [comment]
Both sites are currently broken. http://dcjones.github.io/Gadfly.jl/ redirects to http://gadfly.org which doesn't work. 😕

**Comment by tlnagy** [comment]
Not sure what is going on. The github.io domain was working earlier today.

**Comment by tlnagy** [comment]
I opened a new issue #896 for tracking this. In the mean time, I have a semi recent version of the docs at http://tamasnagy.com/Gadfly.jl/

**Comment by tlnagy** [comment]
So I alerted Daniel to the problem, he said he updated the doc links last night so that's probably the culprit. He hopes to push a fix tonight.

**Comment by tlnagy** [comment]
http://gadfly.org now points to https://dcjones.github.io/Gadfly.jl/ and should stay synced in the future.
