### ISSUE TITLE
Contour plot of 2D Distribution pdf

### ISSUE THREAD

**Issue by jianghaizhu** [dcjones/Gadfly.jl#835]
Hi, 

I want to plot some pdfs for a certain distributions. It is easy for univariate distributions. 

```
using Gadfly
using Distributions

plot(x -> pdf(Normal(0.5, 1.5), x), -5, 5)
```

But how do I plot a 2D distribution pdf using contour? Say, I want a bivariate normal distribution.

```
μ = [2.8, 75]
σ = [0.8 7; 7 70]
d = MvNormal(μ, σ)
```

**Comment by Mattriks** [comment]
```julia
a = linspace(-5.0, 5.0, 20)
plot(z=(x,y) -> pdf(MvNormal(u,s),[x, y]), x=a+u[1], y=a+u[2], Geom.contour)

```
works for me, with suitable values of s.

**Comment by jianghaizhu** [comment]
Thanks a lot. I also found the following works well.

`plot((x, y) -> pdf(MvNormal(μ, σ), [x, y]), -1, 6, 40, 120, Geom.contour)`
