### ISSUE TITLE
Gadfly changes Base.range printing

### ISSUE THREAD

**Issue by cstjean** [dcjones/Gadfly.jl#851]
Normally, `display(UnitRange[1:3000, 5:6])` prints the ranges as `1:3000, 5:6`, but

```julia
using Gadfly
display(UnitRange[1:3000, 5:6])
```

will display all numbers from 1 to 3000.

(note: julia#265 means that you can't get both behaviours in the same session)

**Comment by tlnagy** [comment]
I'm not able to reproduce this in Julia 0.4.5 with the latest Gadfly.

**Comment by cstjean** [comment]
Thank you for checking. I investigated further, and it turned out that the problem was in the latest release of Compose.jl, but it has already been fixed on master. There hasn't been a Compose.jl release in five months...

**Comment by tlnagy** [comment]
Maybe ping someone who has commit access to the Compose repo and tell them to release the current master? I'm sure there have been a couple bugs squashed since the last release.
