### ISSUE TITLE
Extra whitespace with multi-line tick marks 

### ISSUE THREAD

**Issue by weijiekoh** [dcjones/Gadfly.jl#857]
I'm facing the same issue that @sjl124 did here: https://github.com/dcjones/Gadfly.jl/issues/436

> Gadfly appears to calculate the size needed for a plot before the word wrapping/newlines are applied to labels. For long labels, this leaves a lot of white space after the newlines are applied.

For example:

![image](https://cloud.githubusercontent.com/assets/17002415/16254888/15a5d5dc-3877-11e6-8fb7-d777d1b1025a.png)

**Comment by tlnagy** [comment]
FYI, I have just opened a PR against `Compose` that should fix this problem.
