### ISSUE TITLE
Changed meaning of .+= in Julia 0.5

### ISSUE THREAD

**Issue by stevengj** [dcjones/Gadfly.jl#864]
Your test code uses `x .+= y`, so you should know that in Julia 0.5 this has changed meaning to be equivalent to `broadcast!(identity, x, x .+ y)`, so that it mutates the `x` array (see JuliaLang/julia#17510 … in Julia 0.6 the whole operation will occur in-place without temporaries).  So `.+` should only be used if the left-hand side is a mutable array, and you don't mind mutating it.

At first glance, this looks like it is okay for you, because you use it in `data .+= stat.range * (rand(rng, length(data)) - 0.5) .* span`, where `data` seems like an array that you don't mind mutating.  But if it were a problem you could always change it to `+=`.

**Comment by stevengj** [comment]
Similarly for `.*=` and `./=`.

**Comment by shashi** [comment]
I missed this issue and didn't know how [my changes](https://github.com/dcjones/Gadfly.jl/commit/da0b6e9aff1ffdc0ef447876fd75807ab7eb2f51) fixed the problem. Thanks! :) There are two occurances of this left:

```
bincounts ./= sum(bincounts) * binwidth
```

I think this is fine?

**Comment by shashi** [comment]
Ah, the error was:

```julia
ERROR: LoadError: MethodError: Cannot `convert` an object of type Float64 to an object of type Gadfly.Stat.Identity
This may have arisen from a call to the constructor Gadfly.Stat.Identity(...),
since type constructors fall back to convert methods.
 in macro expansion at ./broadcast.jl:129 [inlined]
 in macro expansion at ./simdloop.jl:73 [inlined]
 in macro expansion at ./broadcast.jl:123 [inlined]
 in _broadcast!(::Type{Gadfly.Stat.Identity}, ::Array{Float64,1}, ::Tuple{Tuple{Bool}}, ::Tuple{Tuple{Int64}}, ::Tuple{Array{Float64,1}}, ::Type{Val{1}}) at ./broadcast.jl:117
 in broadcast!(::Type{T}, ::Array{Float64,1}, ::Array{Float64,1}) at ./broadcast.jl:172
 in apply_statistic(::Gadfly.Stat.ViolinStatistic, ::Dict{Symbol,Gadfly.ScaleElement}, ::Gadfly.Coord.Cartesian, ::Gadfly.Aesthetics) at /home/shashi/.julia/v0.5/Gadfly/src/statistics.jl:1683
...
```

I now see how this happens... It looks like [this syntactic transform](https://github.com/JuliaLang/julia/blob/master/src/julia-syntax.scm#L1709) just places the identifier `identity` as the first argument to `broadcast!` which picks up the variable defined [here](https://github.com/dcjones/Gadfly.jl/blob/master/src/statistics.jl#L58) instead...

Maybe the parser should expand it to `Base.identity`?

**Comment by stevengj** [comment]
@shashi, good catch, I'll submit a PR to Julia ASAP.

**Comment by shashi** [comment]
Thanks! I tried editing the scheme file, but couldn't get it t
