### ISSUE TITLE
minvalue and maxvalue for subplot_grid

### ISSUE THREAD

**Issue by ShnitzelKiller** [dcjones/Gadfly.jl#865]
When plotting a subplot grid, it should be possible to force the axis range and scale for all of the subplots at once. Currently the Scale parameter is just ignored.

**Comment by Mattriks** [comment]
Maybe (with `Coord.cartesian`):

```julia
using RDatasets
iris = dataset("datasets","iris")

coord = Coord.cartesian(xmin=0, xmax=10)

p = plot(
melt(iris,[:SepalLength, :Species]), x=:SepalLength,
ygroup=:variable,
    Geom.subplot_grid( coord,
        layer(y=:value, Geom.point, color=:Species),
        free_y_axis = true
    ),
    Guide.title("Iris Data"),
    Guide.colorkey("Species"),
)

draw(PNG(3.3inch,6.6inch),p)

```

**Comment by tlnagy** [comment]
@Mattriks @shashi I feel like this is a very common misunderstanding of `Scale` vs `Coord`, maybe we can clarify the distinction between these two choices in the documentation.

**Comment by Mattriks** [comment]
I agree.  The current doc does mention this ([Scale.x_continuous](https://dcjones.github.io/Gadfly.jl/scale_x_continuous.html)), but providing more explanation on the difference, e.g. that `Scale` is a soft bound and `Coord` is a hard bound. would be useful.

**Comment by tlnagy** [comment]
How's this: http://tamasnagy.com/Gadfly.jl/lib/scales/scale_x_continuous.html#Scale.x_continuous-1 ?
