### ISSUE TITLE
both xlabel and ylabel with Geom.bar

### ISSUE THREAD

**Issue by bjarthur** [dcjones/Gadfly.jl#871]
Geom.bar works fine with either Guide.xlabel or Guide.ylabel, but not both.  Geom.line works in all cases.

```
julia> plot(x=1:10, y=1:10, Geom.bar, Guide.xlabel("foo"))

julia> plot(x=1:10, y=1:10, Geom.bar, Guide.ylabel("foo"))

julia> plot(x=1:10, y=1:10, Geom.bar, Guide.xlabel("foo"), Guide.ylabel("foo"))
ERROR: MethodError: Gadfly.#plot(::Array{Any,1}, ::Gadfly.#plot, ::Gadfly.Geom.#bar, ::Gadfly.Guide.XLabel, ::Gadfly.Guide.YLabel) is ambiguous. Candidates:
  (::Gadfly.#kw##plot)(::Array{Any,1}, ::Gadfly.#plot, f::Function, a, b, elements::Union{DataType,Function,Gadfly.Element,Gadfly.Theme}...)
  (::Gadfly.#kw##plot)(::Array{Any,1}, ::Gadfly.#plot, elements::Union{Array{Gadfly.Layer,1},Union{DataType,Function,Gadfly.Element,Gadfly.Theme}}...)

julia> plot(x=1:10, y=1:10, Geom.line, Guide.xlabel("foo"), Guide.ylabel("foo"))
```

**Comment by tlnagy** [comment]
I can reproduce this with Gadfly v0.4.3 on julia v0.5-rc2. I'm not familiar enough with Julia's internals to debug this right now. Maybe @Mattriks knows?

**Comment by Mattriks** [comment]
The issue is that `Geom.bar` can be misinterpreted as `Function` [Geom.bar](https://github.com/dcjones/Gadfly.jl/blob/master/src/geom/bar.jl), and not as an instance of the type `Gadfly.Geom.BarGeometry` as it should be interpreted. Here is an example:

```julia
test(x::Function) = print("$x is a Function")
test(Geom.bar)
test(Geom.bar())
```
So the following should work:
```julia
plot(x=1:10, y=21:30, Geom.bar(), 
Guide.ylabel("ylabel"), Guide.xlabel("xlabel"))
```
because `Geom.bar()` is an instance of the type `Gadfly.Geom.BarGeometry` .

**Comment by tlnagy** [comment]
Working off of @Mattriks's sleuthing, I just submitted a patch fixing this to master.
