### ISSUE TITLE
Warnings on using Gadfly statement

### ISSUE THREAD

**Issue by jacksaarden** [dcjones/Gadfly.jl#872]
In this morning's interactive session I came across the following warnings, and was unable to use Gadfly.  I've included a text file of the Julia session, as well as a cut and past of the output.  Any assistance would be appreciated.
[Gadfly Warnings.txt](https://github.com/dcjones/Gadfly.jl/files/427054/Gadfly.Warnings.txt)

julia> workspace()

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating Homebrew...
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> using Gadfly
WARNING: Method definition readavailable(Main.Base.IOStream) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:927 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:936.
WARNING: Method definition readavailable(Main.Base.AbstractIOBuffer{Array{UInt8, 1}}) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:928 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:937.
WARNING: Method definition write(Main.Base.IO, Main.Base.IO) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:931 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:940.
WARNING: Method definition write(AbstractString, Any...) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:920 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:929.
WARNING: Method definition readlines(AbstractString) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:926 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:935.
WARNING: Method definition readline(AbstractString) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:925 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:934.
WARNING: Method definition cov(AbstractArray{T<:Any, 1}, AbstractArray{T<:Any, 1}, Bool) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:905 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:914.
WARNING: Method definition cov(AbstractArray{T<:Any, 2}, AbstractArray{T<:Any, 2}, Integer) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:906 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:915.
WARNING: Method definition cov(AbstractArray{T<:Any, 2}, AbstractArray{T<:Any, 2}, Integer, Bool) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:907 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:916.
WARNING: Method definition cov(AbstractArray{T<:Any, 1}, Bool) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:902 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:911.
WARNING: Method definition cov(AbstractArray{T<:Any, 2}, Integer) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:903 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:912.
WARNING: Method definition cov(AbstractArray{T<:Any, 2}, Integer, Bool) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:904 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:913.
WARNING: Method definition remotecall_wait(Function, Main.Base.LocalProcess, Any...) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:844 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:853.
WARNING: Method definition remotecall_wait(Function, Main.Base.Worker, Any...) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:845 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:854.
WARNING: Method definition remotecall_wait(Function, Integer, Any...) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:846 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:855.
WARNING: Method definition precision(Type{Main.Base.MPFR.BigFloat}) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:968 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:977.
WARNING: Method definition remotecall(Function, Main.Base.LocalProcess, Any...) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:844 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:853.
WARNING: Method definition remotecall(Function, Main.Base.Worker, Any...) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:845 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:854.
WARNING: Method definition remotecall(Function, Integer, Any...) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:846 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:855.
WARNING: Method definition readuntil(AbstractString, Any...) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:924 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:933.
WARNING: Method definition eachline(AbstractString) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:937 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:946.
WARNING: Method definition cor(AbstractArray{T<:Any, 2}, AbstractArray{T<:Any, 2}, Integer) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:910 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:919.
WARNING: Method definition cor(AbstractArray{T<:Any, 2}, Integer) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:909 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:918.
WARNING: Method definition read(Main.Base.IO) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:917 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:926.
WARNING: Method definition read(Main.Base.IO, Any) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:918 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:927.
WARNING: Method definition read(AbstractString, Any...) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:922 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:931.
WARNING: Method definition call(Type{Symbol}, Any...) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:400 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:408.
WARNING: Method definition call(Type{Union{UTF8String, ASCIIString}}, Main.Base.AbstractIOBuffer{T<:AbstractArray{UInt8, 1}}) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:1278 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:1354.
WARNING: Method definition call(Type{Union{UTF8String, ASCIIString}}, Main.Base.Cstring) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:1283 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:1359.
WARNING: Method definition call(Type{Union{UTF8String, ASCIIString}}, Array{UInt8, 1}) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:1284 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:1360.
WARNING: Method definition call(Type{Union{UTF8String, ASCIIString}}, Union{Ptr{UInt8}, Ptr{Int8}}) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:1285 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:1361.
WARNING: Method definition call(Type{Union{UTF8String, ASCIIString}}, Union{Ptr{UInt8}, Ptr{Int8}}, Integer) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:1286 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:1362.
WARNING: Method definition call(Type{Union{UTF8String, ASCIIString}}, AbstractString) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:1287 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:1363.
WARNING: Method definition remotecall_fetch(Function, Main.Base.LocalProcess, Any...) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:844 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:853.
WARNING: Method definition remotecall_fetch(Function, Main.Base.Worker, Any...) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:845 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:854.
WARNING: Method definition remotecall_fetch(Function, Integer, Any...) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:846 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:855.
WARNING: Method definition read!(AbstractString, Any) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:923 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:932.
WARNING: Method definition remote_do(Function, Main.Base.LocalProcess, Any...) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:844 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:853.
WARNING: Method definition remote_do(Function, Main.Base.Worker, Any...) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:845 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:854.
WARNING: Method definition remote_do(Function, Integer, Any...) in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:846 overwritten in module Compat at /Users/Aaron/.julia/Compat/src/Compat.jl:855.
INFO: Recompiling stale cache file /Users/Aaron/.julia/lib/v0.4/Gadfly.ji for module Gadfly.
INFO: Recompiling stale cache file /Users/Aaron/.julia/lib/v0.4/ColorTypes.ji for module ColorTypes.
INFO: Recompiling stale cache file /Users/Aaron/.julia/lib/v0.4/Colors.ji for module Colors.
INFO: Recompiling stale cache file /Users/Aaron/.julia/lib/v0.4/Graphics.ji for module Graphics.
INFO: Recompiling stale cache file /Users/Aaron/.julia/lib/v0.4/Compose.ji for module Compose.
INFO: Recompiling stale cache file /Users/Aaron/.julia/lib/v0.4/Cairo.ji for module Cairo.
WARNING: New definition 
    +(AbstractArray{T<:Any, 2}, WoodburyMatrices.SymWoodbury) at /Users/Aaron/.julia/WoodburyMatrices/src/SymWoodburyMatrices.jl:106
is ambiguous with: 
    +(DataArrays.DataArray, AbstractArray) at /Users/Aaron/.julia/DataArrays/src/operators.jl:276.
To fix, define 
    +(DataArrays.DataArray{T<:Any, 2}, WoodburyMatrices.SymWoodbury)
before the new definition.
WARNING: New definition 
    +(AbstractArray{T<:Any, 2}, WoodburyMatrices.SymWoodbury) at /Users/Aaron/.julia/WoodburyMatrices/src/SymWoodburyMatrices.jl:106
is ambiguous with: 
    +(DataArrays.AbstractDataArray, AbstractArray) at /Users/Aaron/.julia/DataArrays/src/operators.jl:300.
To fix, define 
    +(DataArrays.AbstractDataArray{T<:Any, 2}, WoodburyMatrices.SymWoodbury)
before the new definition.
WARNING: Method definition ctranspose(Function) in module Calculus at /Users/Aaron/.julia/Calculus/src/derivative.jl:26 overwritten in module Calculus at /Users/Aaron/.julia/Calculus/src/derivative.jl:26.
WARNING: Method definition gradient(Function) in module Calculus at /Users/Aaron/.julia/Calculus/src/derivative.jl:22 overwritten in module Calculus at /Users/Aaron/.julia/Calculus/src/derivative.jl:22.
WARNING: Method definition gradient(Function, Union{Array{#T<:Number, 1}, #T<:Number}) in module Calculus at /Users/Aaron/.julia/Calculus/src/derivative.jl:17 overwritten in module Calculus at /Users/Aaron/.julia/Calculus/src/derivative.jl:17.
WARNING: Method definition gradient(Function, Union{Array{#T<:Number, 1}, #T<:Number}, Symbol) in module Calculus at /Users/Aaron/.julia/Calculus/src/derivative.jl:17 overwritten in module Calculus at /Users/Aaron/.julia/Calculus/src/derivative.jl:17.
WARNING: Method definition gradient(Function, Symbol) in module Calculus at /Users/Aaron/.julia/Calculus/src/derivative.jl:22 overwritten in module Calculus at /Users/Aaron/.julia/Calculus/src/derivative.jl:22.
WARNING: New definition 
    +(AbstractArray{T<:Any, 2}, WoodburyMatrices.SymWoodbury) at /Users/Aaron/.julia/WoodburyMatrices/src/SymWoodburyMatrices.jl:106
is ambiguous with: 
    +(DataArrays.DataArray, AbstractArray) at /Users/Aaron/.julia/DataArrays/src/operators.jl:276.
To fix, define 
    +(DataArrays.DataArray{T<:Any, 2}, WoodburyMatrices.SymWoodbury)
before the new definition.
WARNING: New definition 
    +(AbstractArray{T<:Any, 2}, WoodburyMatrices.SymWoodbury) at /Users/Aaron/.julia/WoodburyMatrices/src/SymWoodburyMatrices.jl:106
is ambiguous with: 
    +(DataArrays.AbstractDataArray, AbstractArray) at /Users/Aaron/.julia/DataArrays/src/operators.jl:300.
To fix, define 
    +(DataArrays.AbstractDataArray{T<:Any, 2}, WoodburyMatrices.SymWoodbury)
before the new definition.

julia>

**Comment by tlnagy** [comment]
These warnings are due to Julia 0.4 throwing an error when an imported method is ambiguous with   another method. This is fixed in the next version of Julia 0.5: https://github.com/JuliaLang/julia/pull/16125 It is unlikely that this will be backported, see https://github.com/timholy/WoodburyMatrices.jl/issues/13.
