### ISSUE TITLE
Proposal: Switch Gadfly Docs to Documenter.jl

### ISSUE THREAD

**Issue by tlnagy** [dcjones/Gadfly.jl#878]
It looks like `Documenter.jl` is gaining momentum as the de facto Julia documentation generator. It would be nice to move Gadfly's docs away from `Judo.jl` since it hasn't been touched in roughly two years. `Compose.jl` is already moving in that direction with @Hydrotoast's work in https://github.com/dcjones/Compose.jl/pull/214. 

@rsrock, @shashi, what do you all think?

**Comment by rsrock** [comment]
Absolutely, this is a good idea.

**Comment by Hydrotoast** [comment]
I think the only task left is to fix the logo if someone can figure out
what the old logo looks like.

**Comment by tlnagy** [comment]
> I think the only task left is to fix the logo if someone can figure out what the old logo looks like.

Gadfly's logo? Or Compose's?

**Comment by Hydrotoast** [comment]
Compose.jl -- if you see the screenshot in my PR, it looks broken. Since
the composejl.org site is down, i can't verify whether it is correct.

**Comment by tlnagy** [comment]
Progress here: https://github.com/dcjones/Gadfly.jl/pull/879
