### ISSUE TITLE
MethodError with colorkey and discrete colors on 0.5

### ISSUE THREAD

**Issue by brian-j-smith** [dcjones/Gadfly.jl#881]
Using ``Scale.color_discrete()`` and ``Guide.colorkey()`` together to have a discrete set of colors in a plot and a key to summarize them works in julia 0.4 but produces a MethodError in 0.5.  Below is an example, the resulting error, and my version info.

```julia
julia> n = 1000
julia> plot(x=[rand(n); rand(n)], Geom.histogram,
            color=repeat([1, 2], inner=[n]),
            Scale.color_discrete(),
            Guide.colorkey("Label"))
ERROR: MethodError: Gadfly.#plot(::Array{Any,1}, ::Gadfly.#plot, ::Gadfly.Geom.#
histogram, ::Gadfly.Scale.DiscreteColorScale, ::Gadfly.Guide.ColorKey) is ambigu
ous. Candidates:
  (::Gadfly.#kw##plot)(::Array{Any,1}, ::Gadfly.#plot, f::Function, a, b, elemen
ts::Union{DataType,Function,Gadfly.Element,Gadfly.Theme}...)
  (::Gadfly.#kw##plot)(::Array{Any,1}, ::Gadfly.#plot, elements::Union{Array{Gad
fly.Layer,1},Union{DataType,Function,Gadfly.Element,Gadfly.Theme}}...)

julia> versioninfo()
Julia Version 0.5.0-rc3+0
Commit e6f843b (2016-08-22 23:43 UTC)
Platform Info:
  System: NT (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

**Comment by tlnagy** [comment]
Try doing `Geom.histogram()` instead of `Geom.histogram`, does that fix your problem?

**Comment by brian-j-smith** [comment]
Amazing!  Adding parentheses did indeed fix the problem.  Thanks for the solution.

**Comment by tlnagy** [comment]
>  Thanks for the solution.

you're welcome! Though to be honest, my solution isn't a real one as it doesn't fix the underlying problem. See #882.

**Comment by brian-j-smith** [comment]
I see.  That's helpful to know what the underlying problem is and why the "solution" worked.

**Comment by tlnagy** [comment]
Now that #883 has merged, your original code should work on master.

**Comment by brian-j-smith** [comment]
Yep, my original (Mamba package) code works with your changes.  :+1:  on the help and ultimately fixing the underlying issue.
