### ISSUE TITLE
Docs are down

### ISSUE THREAD

**Issue by tlnagy** [dcjones/Gadfly.jl#896]
Both https://dcjones.github.io/Gadfly.jl/latest and http://gadflyjl.org are stuck in redirect loops. Not much that I can do until @dcjones fixes this. In the mean time a somewhat functionally complete copy is available at http://tamasnagy.com/Gadfly.jl/

**Comment by tlnagy** [comment]
I added a link to main README in case people don't see it here with 0c50487e0f7e888f845a1ffc2d021d84db7219d5. This should be reverted when the docs come back up.

**Comment by tlnagy** [comment]
As I mentioned [here](https://github.com/dcjones/Gadfly.jl/issues/832#issuecomment-246548908), I alerted Daniel (the package owner) to the problem, he said he updated the doc links last night so that's probably the culprit. He hopes to push a fix tonight.

**Comment by rsrock** [comment]
While you have him, can you get him to remove the doc link just below the title of the repo?  Just after "Crafty...", and he's the only one with the power to do that.

**Comment by tlnagy** [comment]
I was thinking that if we got the http://gadflyjl.org domain to point to http://dcjones.github.io/Gadfly.jl/ (which collaborators have access to) then we get best of both worlds. No?

**Comment by tlnagy** [comment]
Docs are back up!
