### ISSUE TITLE
Documentation Bug?

### ISSUE THREAD

**Issue by AStupidBear** [dcjones/Gadfly.jl#899]
![image](https://cloud.githubusercontent.com/assets/16422976/18616312/13c5b7fe-7dec-11e6-92c4-57a6635de393.png)

**Comment by tlnagy** [comment]
This was an upstream bug that was patched a couple days ago: https://github.com/JuliaDocs/Documenter.jl/pull/269. It looks like the docs were built before that fix was pushed out. I just started a rebuild, hopefully it fixes this.

**Comment by tlnagy** [comment]
This now fixed on the latest docs: http://gadflyjl.org/latest/
