### ISSUE TITLE
julia 0.5

### ISSUE THREAD

**Issue by montyvesselinov** [dcjones/Gadfly.jl#904]
Under 0.4 only the first gadfly call is slow. Under 0.5 all the gadfly calls are slow. Is this specific to my code or is a general issue. We use Gadfly extensively in MADS http://madsjulia.github.io/Mads.jl/

**Comment by lobingera** [comment]
Can you give some more background on 'your code' or what the package specifically calls in Gadfly or some kind of rough time measurement?

**Comment by montyvesselinov** [comment]
Here is an example:

```
		MArows = 5
		MAcols = Int(ceil(numwells/5))
		MA = Array(Compose.Context, (MArows, MAcols))
		i = 1
		for w in wellorder
			@time MA[i] = Gadfly.render(Gadfly.spy(b[:,source_index], Gadfly.Guide.title(wellnameorder[i]), Gadfly.Scale.y_discrete(labels = i->uniquespecies[i]), Gadfly.Scale.x_discrete,
					Gadfly.Guide.YLabel("Species"), Gadfly.Guide.XLabel("Sources"), Gadfly.Guide.colorkey(""),
					Gadfly.Theme(default_point_size=20Gadfly.pt, major_label_font_size=14Gadfly.pt, minor_label_font_size=12Gadfly.pt, key_title_font_size=16Gadfly.pt, key_label_font_size=12Gadfly.pt),
					Gadfly.Scale.ContinuousColorScale(Gadfly.Scale.lab_gradient(parse(Colors.Colorant, "green"), parse(Colors.Colorant, "yellow"), parse(Colors.Colorant, "red")), minvalue = 0, maxvalue = 1)))
			i += 1
		end
		for w in numwells+1:MArows*MAcols
			MA[w] = Compose.context()
		end
		gs = Gadfly.gridstack(MA)
		filename = "results/$(casestring)-$numbuckets-$retries-wellmixtures.svg"
		@time Gadfly.draw(Gadfly.SVG(filename, MArows * 3Gadfly.inch, MAcols * 6Gadfly.inch), gs)
		filename = "results/$(casestring)-$numbuckets-$retries-wellmixtures.png"
		@time Gadfly.draw(Gadfly.PNG(filename, MArows * 3Gadfly.inch, MAcols * 6Gadfly.inch), gs)
```

v0.5 time:
  0.676830 seconds (4.46 M allocations: 77.923 MB, 3.67% gc time)
  0.667589 seconds (4.46 M allocations: 77.889 MB, 3.07% gc time)
  0.671891 seconds (4.46 M allocations: 77.890 MB, 2.39% gc time)
  0.677189 seconds (4.46 M allocations: 77.890 MB, 3.11% gc time)
  0.659317 seconds (4.46 M allocations: 77.890 MB, 2.41% gc time)
  0.658482 seconds (4.46 M allocations: 77.890 MB, 3.30% gc time)
  0.660694 seconds (4.46 M allocations: 77.890 MB, 2.37% gc time)
  0.864375 seconds (4.46 M allocations: 77.891 MB, 24.52% gc time)
  0.659093 seconds (4.46 M allocations: 77.890 MB, 2.22% gc time)
  0.663471 seconds (4.46 M allocations: 77.890 MB, 3.07% gc time)
  0.670146 seconds (4.46 M allocations: 77.890 MB, 2.93% gc time)
  0.702045 seconds (4.46 M allocations: 77.891 MB, 2.27% gc time)
  0.687690 seconds (4.46 M allocations: 77.891 MB, 2.95% gc time)
  0.678832 seconds (4.46 M allocations: 77.891 MB, 2.24% gc time)
  0.663035 seconds (4.46 M allocations: 77.891 MB, 3.02% gc time)
  0.665496 seconds (4.46 M allocations: 77.890 MB, 2.49% gc time)
  0.689027 seconds (4.46 M allocations: 77.891 MB, 3.02% gc time)
  0.683301 seconds (4.46 M allocations: 77.891 MB, 3.03% gc time)
  0.663019 seconds (4.46 M allocations: 77.891 MB, 2.37% gc time)
  4.239023 seconds (27.05 M allocations: 483.293 MB, 2.84% gc time)
  4.340858 seconds (26.26 M allocations: 469.516 MB, 2.73% gc time)

0.4 time:
  0.012330 seconds (17.77 k allocations: 590.201 KB)
  0.004448 seconds (17.73 k allocations: 588.469 KB)
  0.004018 seconds (17.75 k allocations: 588.938 KB)
  0.004360 seconds (17.75 k allocations: 588.938 KB)
  0.004514 seconds (17.74 k allocations: 588.625 KB)
  0.004370 seconds (17.74 k allocations: 588.625 KB)
  0.004253 seconds (17.75 k allocations: 588.938 KB)
  0.004117 seconds (17.75 k allocations: 588.938 KB)
  0.004301 seconds (17.75 k allocations: 588.938 KB)
  0.004388 seconds (17.74 k allocations: 588.625 KB)
  0.004993 seconds (17.74 k allocations: 588.625 KB)
  0.004460 seconds (17.75 k allocations: 588.938 KB)
  0.004441 seconds (17.75 k allocations: 588.938 KB)
  0.004383 seconds (17.74 k allocations: 588.625 KB)
  0.004225 seconds (17.75 k allocations: 588.938 KB)
  0.004396 seconds (17.75 k allocations: 588.938 KB)
  0.004568 seconds (17.75 k allocations: 588.938 KB)
  0.004211 seconds (17.75 k allocations: 588.938 KB)
  0.004230 seconds (17.75 k allocations: 588.938 KB)
  0.046988 seconds (210.02 k allocations: 8.317 MB)
  0.318117 seconds (186.49 k allocations: 7.202 MB, 2.91% gc time)

**Comment by tbreloff** [comment]
Wow that's a serious wall of text in your example!  If you're interested in comparing other packages, the Plots commands will be something like:

```julia
using Plots
gr() # load a backend of your choosing

# this is unfinished, but you get the idea
plot([heatmap(mat[i], yguide = "Species", fill = cgrad([:green,:yellow,:red]), <more_attributes>) for i=1:n]...)
```

Here's an example:

```julia
using Plots; pyplot()
plot([heatmap(rand(10,10), yguide="Y", fill=cgrad([:green,:yellow,:red]), leg=false) for i=1:9]...)
```

![tmp](https://cloud.githubusercontent.com/assets/933338/18922062/36cca1fa-8575-11e6-97da-031357ec0202.png)

**Comment by lobingera** [comment]
@tbreloff ?

**Comment by montyvesselinov** [comment]
cool. we plan to move away from Gadfly to Plots (especially using plotly.js as a backend) but we do lack resources to change all the Gadfly coding already in.

**Comment by Mattriks** [comment]
And here is another way in Gadfly:

```julia
using DataFrames
m = vcat([ [x y] for x=1:10, y=1:10 ]...)
D = vcat([DataFrame(x=m[:,1], y=m[:,2], z=rand(100), row=r, col=c) for r in ["d","e","f"], c in ["a","b","c"]]...)

mytheme = Theme(major_label_font_size=14pt, minor_label_font_size=12pt,
    key_title_font_size=16pt, key_label_font_size=12pt)
cscale = Scale.lab_gradient(colorant"green", colorant"yellow", colorant"red")
coord = Coord.cartesian(xmin=1, ymin=1, xmax=10, ymax=10)

p = plot(D, x=:x, y=:y, color=:z, xgroup = :col, ygroup=:row, 
    Geom.subplot_grid(coord, Geom.rectbin), 
    Scale.color_continuous(colormap=cscale), 
    Guide.xlabel("Sources"), Guide.ylabel("Species"),
    mytheme )
```
![issue904](https://cloud.githubusercontent.com/assets/18226881/18938447/f3fbfffc-863b-11e6-9561-741f2a913d9a.png)

Note that you can move or add various arguments into  `Geom.subplot_grid()`. For example, `Geom.subplot.grid(Guide.xlabel("Sources"), xgroup=:col, ygroup=:row, etc)`. Try different combinations to see the effect!

**Comment by montyvesselinov** [comment]
All of these are great suggestions. However, my concern is not that much the graph design but the execution times under julia 0.5. the gadfly performance under v0.5 substantially deteriorated.

**Comment by Mattriks** [comment]
Just out of interest, I timed the `p=plot` statement of my `Geom.subplot_grid` example above (two times) and got the following results: 

Julia 0.5.0:
0.868200 seconds (562.47 k allocations: 23.395 MB, 0.83% gc time) 
0.000191 seconds (169 allocations: 13.625 KB) 

Julia 0.4.6
0.828494 seconds (734.70 k allocations: 28.513 MB, 0.51% gc time) 
0.000133 seconds (162 allocations: 11.797 KB)

**Comment by montyvesselinov** [comment]
i did more tests about this issue.

the following code crashes and produces a segmentation fault on 0.5.

```
import Gadfly
b = rand(10,10)
for i in 1:1
#gs = Gadfly.spy(b)
gs = Gadfly.spy(b, Gadfly.Guide.title("w"),
    Gadfly.Guide.YLabel("Species"), Gadfly.Guide.XLabel("Sources"), Gadfly.Guide.colorkey(""),
    Gadfly.Theme(default_point_size=20Gadfly.pt, major_label_font_size=14Gadfly.pt, minor_label_font_size=12Gadfly.pt, key_title_font_size=16Gadfly.pt, key_label_font_size=12Gadfly.pt),
    Gadfly.Scale.ContinuousColorScale(Gadfly.Scale.lab_gradient(parse(Colors.Colorant, "green"), parse(Colors.Colorant, "yellow"), parse(Colors.Colorant, "red")), minvalue = 0, maxvalue = 1)
    )
end
```

if you remove the `for` loop it works ok.

if you comment out `Gadfly.Scale.ContinuousColorScale(Gadfly.Scale.lab_gradient(parse(Colors.Colorant, "green"), parse(Colors.Colorant, "yellow"), parse(Colors.Colorant, "red")), minvalue = 0, maxvalue = 1)`

also works.

something is very strange.

**Comment by Mattriks** [comment]
The following works for me on Julia 0.5.0:
```julia
using Gadfly
cscale = Scale.lab_gradient(colorant"green", colorant"yellow", colorant"red")
mytheme = Theme(default_point_size=20pt, major_label_font_size=14pt, minor_label_font_size=12pt,
key_title_font_size=16pt, key_label_font_size=12pt)

# here x and y are discrete
m = vcat([["$x" "$y"] for x in 1:10, y in 1:10]...)
b = rand(10,10)

for i in 1:1
    p = plot(x=m[:,1], y=m[:,2], color=vec(b), Geom.rectbin,
        Guide.title("w"), Guide.colorkey(""),
        Guide.xlabel("Species"), Guide.ylabel("Sources"),
        Scale.ContinuousColorScale(cscale, minvalue=0, maxvalue=1),
    mytheme)
end
```

**Comment by montyvesselinov** [comment]
This is a Julia problem. Not a Gadfly problem

https://github.com/JuliaLang/julia/issues/18749
