### ISSUE TITLE
Gadfly.Scale.x_discrete

### ISSUE THREAD

**Issue by montyvesselinov** [dcjones/Gadfly.jl#913]
How Gadfly.Scale.x_discrete labels can be forced to be horizontal?

**Comment by tlnagy** [comment]
I don't think they can be currently.

**Comment by Mattriks** [comment]
Using `Guide.xticks(orientation=:horizontal)` with `Scale.x_discrete(labels= )` works for me.

**Comment by tlnagy** [comment]
Ah, I always forget whether certain things belong to `Guides` or `Scales`. Good catch @Mattriks.
